(()=>{
'use strict';
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').trim();
const digits=v=>String(v??'').replace(/\D/g,'');
function keyOf(d){return [digits(d.cpf),norm(d.data),norm(d.produto).toLowerCase(),norm(d.capacidade).toLowerCase()].join('|')}
function ensureImportBox(){const grid=$('settingsPanel')?.querySelector('.settings-grid');if(!grid||$('bulkImportBox'))return;const box=document.createElement('div');box.className='settings-box';box.id='bulkImportBox';box.innerHTML='<h3>Importação em lote</h3><div class="muted-box">Importe várias pré-vendas de uma vez usando um arquivo JSON preparado para o sistema. Registros já existentes são ignorados automaticamente.</div><div class="row-actions"><label class="btn-outline" style="cursor:pointer">Importar pré-vendas<input id="bulkImportFile" type="file" accept="application/json,.json" style="display:none"></label></div><div id="bulkImportStatus" class="field-help"></div>';grid.appendChild(box);$('bulkImportFile').onchange=importFile}
async function importFile(e){if(!(await requestAdmin('importar pré-vendas em lote')))return;const file=e.target.files?.[0];if(!file)return;const status=$('bulkImportStatus');try{const parsed=JSON.parse(await file.text());const rows=Array.isArray(parsed)?parsed:Array.isArray(parsed.history)?parsed.history:null;if(!rows)throw new Error('Formato de arquivo incompatível.');const current=getHistory();const existing=new Set(current.map(keyOf));const now=new Date().toISOString();let added=0,skipped=0;const incoming=[];for(const src of rows){if(!src||!src.cliente||!src.cpf||!src.produto)continue;const d={id:crypto.randomUUID(),numero:'',valor:norm(src.valor),data:norm(src.data),cliente:norm(src.cliente),cpf:norm(src.cpf),produto:norm(src.produto),capacidade:norm(src.capacidade),cor:norm(src.cor),vendedor:norm(src.vendedor),preregistro:norm(src.preregistro),trocafone:norm(src.trocafone),obsInterna:norm(src.obsInterna),wearable:norm(src.wearable),wearableColor:norm(src.wearableColor),statusVenda:norm(src.statusVenda)||'Aguardando produto',updatedAt:now};const k=keyOf(d);if(existing.has(k)){skipped++;continue}existing.add(k);incoming.push(d);added++}if(!incoming.length){status.textContent=`Nenhuma nova pré-venda. ${skipped} registro(s) já existiam.`;return}setHistory(mergeHistory(current,incoming));renderHistory();renderDashboard();if(typeof renderWithdrawals==='function')renderWithdrawals();try{await upsertHistory(incoming);setOnlineState('ok','Online');status.textContent=`Importação concluída: ${added} adicionada(s), ${skipped} ignorada(s) por duplicidade.`}catch(err){console.error(err);setOnlineState('off','Sync pendente');status.textContent=`${added} adicionada(s) neste aparelho. A sincronização online ficou pendente.`}}
catch(err){alert('Não foi possível importar: '+err.message)}finally{e.target.value=''}}
ensureImportBox();const oldSwitch=window.switchTab;window.switchTab=function(id){oldSwitch(id);if(id==='settingsPanel')ensureImportBox()};
})();
