(()=>{
'use strict';
const $=id=>document.getElementById(id);
const wearableRx=/galaxy\s*(watch|buds|ring|fit)/i;
const galaxyZRx=/galaxy\s*z\s*(flip|fold)/i;
const esc=s=>typeof escapeHtml==='function'?escapeHtml(s):String(s||'');
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const isWearable=p=>wearableRx.test(p?.name||'');
const isGalaxyZ=p=>galaxyZRx.test(p?.name||'');
function baseName(p){let n=String(p?.name||'').trim();for(const c of uniq(p?.colors||[]).sort((a,b)=>String(b).length-String(a).length)){n=n.replace(new RegExp('\\s+'+String(c).replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')+'$','i'),'').trim()}return n}
function groups(){const m=new Map();for(const p of getCatalog().filter(isWearable)){const n=baseName(p);if(!m.has(n))m.set(n,{name:n,colors:[]});m.get(n).colors=uniq([...m.get(n).colors,...(p.colors||[])])}return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))}
function ensure(){if($('wearable'))return;const prod=$('produto')?.closest('.field'),cor=$('cor')?.closest('.field');if(!prod||!cor)return;prod.querySelector('label').textContent='Galaxy Z *';const t=document.createElement('div');t.className='eco-title';t.innerHTML='Ecossistema <span>opcional</span>';const a=document.createElement('div');a.className='field';a.innerHTML='<label for="wearable">Galaxy Wearable</label><select id="wearable"><option value="">Nenhum wearable</option></select>';const b=document.createElement('div');b.className='field';b.innerHTML='<label for="wearableColor">Cor</label><select id="wearableColor" disabled><option value="">Selecione o wearable primeiro</option></select>';cor.after(t,a,b);$('wearable').addEventListener('change',()=>colors())}
function models(selected='',selectedColor=''){ensure();const el=$('wearable');if(!el)return;const list=groups();el.innerHTML='<option value="">Nenhum wearable</option>'+list.map(x=>`<option>${esc(x.name)}</option>`).join('');if(selected&&!list.some(x=>x.name===selected))el.insertAdjacentHTML('beforeend',`<option>${esc(selected)}</option>`);if(selected)el.value=selected;colors(selectedColor)}
function colors(selected=''){const m=$('wearable'),c=$('wearableColor');if(!m||!c)return;const g=groups().find(x=>x.name===m.value);if(!g){c.disabled=true;c.innerHTML='<option value="">Selecione o wearable primeiro</option>';return}c.disabled=false;c.innerHTML='<option value="">Selecione</option>'+g.colors.map(x=>`<option>${esc(x)}</option>`).join('');if(selected&&g.colors.includes(selected))c.value=selected;else if(g.colors.length===1)c.value=g.colors[0]}
window.populateProducts=function(selected=''){ensure();const el=$('produto'),list=getCatalog().filter(isGalaxyZ);el.innerHTML='<option value="">Selecione um Galaxy Z</option>'+list.map(p=>`<option>${esc(p.name)}</option>`).join('');if(selected&&!list.some(p=>p.name===selected))el.insertAdjacentHTML('beforeend',`<option>${esc(selected)}</option>`);if(selected)el.value=selected;onProductChange();models()};
const collect0=window.collect;window.collect=function(){const d=collect0();d.wearable=$('wearable')?.value||'';d.wearableColor=$('wearableColor')?.value||'';return d};
const validate0=window.validate;window.validate=function(d){const e=validate0(d);if(e)return e;if(d.wearable&&!d.wearableColor)return'Selecione a cor do Galaxy Wearable.';return''};
const toDb0=window.toDb;window.toDb=function(d){const r=toDb0(d),clean=String(d.obsInterna||'').replace(/\n?\[\[WEARABLE:.*?\]\]/g,'').trim();r.obs_interna=clean+(d.wearable?'\n[[WEARABLE:'+d.wearable+'|'+(d.wearableColor||'')+']]':'');return r};
const fromDb0=window.fromDb;window.fromDb=function(r){const d=fromDb0(r),m=String(r.obs_interna||'').match(/\[\[WEARABLE:(.*?)(?:\|(.*?))?\]\]/);d.wearable=m?m[1]:'';d.wearableColor=m&&m[2]?m[2]:'';d.obsInterna=String(d.obsInterna||'').replace(/\n?\[\[WEARABLE:.*?\]\]/g,'').trim();return d};
const load0=window.loadRecord;window.loadRecord=async function(id){await load0(id);const d=getHistory().find(x=>x.id===id);models(d?.wearable||'',d?.wearableColor||'')};
const clear0=window.clearForm;window.clearForm=function(){clear0();models('','')};
const doc0=window.renderDoc;window.renderDoc=function(d){doc0(d);let row=$('docWearableRow');if(!row){const grid=$('docProduto')?.closest('.pv-block')?.querySelector('.pv-grid');if(grid){row=document.createElement('div');row.id='docWearableRow';row.className='pv-row full';row.innerHTML='<div class="pv-label">Ecossistema</div><div class="pv-value" id="docWearable">—</div>';grid.appendChild(row)}}if(row){row.style.display=d.wearable?'':'none';if(d.wearable)$('docWearable').textContent=d.wearable+(d.wearableColor?' • '+d.wearableColor:'')}};
const style=document.createElement('style');style.textContent='.eco-title{grid-column:1/-1;margin-top:4px;padding-top:18px;border-top:1px solid #e4e7ec;font-size:13px;font-weight:900;letter-spacing:.6px;text-transform:uppercase;color:#1428A0}.eco-title span{font-size:10px;font-weight:600;color:#98a2b3;margin-left:6px}';document.head.appendChild(style);ensure();models();
const css=document.createElement('link');css.rel='stylesheet';css.href='./v5.css?v=5.0';document.head.appendChild(css);
const css51=document.createElement('link');css51.rel='stylesheet';css51.href='./v51.css?v=5.1';document.head.appendChild(css51);
const script=document.createElement('script');script.src='./v5.js?v=5.0';script.onload=()=>{const s=document.createElement('script');s.src='./v51.js?v=5.1';document.body.appendChild(s)};document.body.appendChild(script);
const f=document.querySelector('.footer-note');if(f)f.textContent='PRE VENDA • v5.1 ONLINE';
})();