(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PHONE='PHONE',RECYCLE_KEY='preVendaRecycleV1',RECYCLE_PREFIX='recycle-pre-sale-v1:',PENDING_KEY='preVendaPendingV1',GOALS_KEY='preVendaGoalsV1',CAMPAIGN_KEY='preVendaCampaignV1',DELETED_KEY='preVendaDeletedRecordsV1',DELETED_PREFIX='deleted-pre-sale-v2:';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:0,maximumFractionDigits:0});
const parse=v=>{try{return JSON.parse(localStorage.getItem(v)||'null')}catch{return null}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const marker=(text,key)=>String(text||'').match(new RegExp('\\[\\['+key+':(.*?)\\]\\]'))?.[1]||'';
const cleanMarker=(text,key)=>String(text||'').replace(new RegExp('\\n?\\[\\['+key+':.*?\\]\\]','g'),'').trim();
const digits=v=>String(v||'').replace(/\D/g,'');
function maskPhone(v){const d=digits(v).slice(0,11);if(d.length<=2)return d?`(${d}`:'';if(d.length<=6)return`(${d.slice(0,2)}) ${d.slice(2)}`;if(d.length<=10)return`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`;return`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`}
function recordValue(r){return Number(window.getPreSaleFinalValue?.(r)||r?.valorFinal||0)}
function device(){return localStorage.getItem('preVendaDeviceIdV1')||'Computador não identificado'}

// Telefone compatível com a base atual: armazenado no campo técnico já existente.
function ensurePhone(){if($('telefone'))return;const cpf=$('cpf')?.closest('.field');if(!cpf)return;const field=document.createElement('div');field.className='field';field.innerHTML='<label for="telefone">Contato do cliente *</label><input id="telefone" inputmode="tel" maxlength="15"><div class="field-help">Informe o DDD e o número do WhatsApp.</div>';cpf.insertAdjacentElement('afterend',field);$('telefone').addEventListener('input',e=>e.target.value=maskPhone(e.target.value))}
ensurePhone();
const collect0=window.collect;window.collect=function(){const d=collect0.apply(this,arguments);d.telefone=$('telefone')?.value.trim()||'';return d};
const validate0=window.validate;window.validate=function(d){const base=validate0.apply(this,arguments);if(base)return base;const n=digits(d.telefone);if(n.length!==10&&n.length!==11)return'Informe o contato do cliente com DDD.';return''};
const toDb0=window.toDb;window.toDb=function(d){const r=toDb0.apply(this,arguments),raw=cleanMarker(r.obs_interna,PHONE);r.obs_interna=[raw,d.telefone?`[[${PHONE}:${digits(d.telefone)}]]`:''].filter(Boolean).join('\n');return r};
const fromDb0=window.fromDb;window.fromDb=function(r){const d=fromDb0.apply(this,arguments),phone=marker(r.obs_interna,PHONE);d.telefone=phone?maskPhone(phone):'';d.obsInterna=cleanMarker(d.obsInterna,PHONE);return d};
const clear0=window.clearForm;window.clearForm=function(){const r=clear0.apply(this,arguments);ensurePhone();if($('telefone'))$('telefone').value='';return r};
function selectValue(id,value,placeholder){const el=$(id);if(!el)return;if(value&&!Array.from(el.options).some(x=>x.value===value))el.insertAdjacentHTML('beforeend',`<option>${esc(value)}</option>`);el.value=value||'';if(value&&el.value!==value){el.innerHTML+=`<option value="${esc(value)}">${esc(value)}</option>`;el.value=value}if(!value&&placeholder&&el.options.length)el.options[0].textContent=placeholder}
function restoreEditFields(d){if(!d)return;ensurePhone();if($('telefone'))$('telefone').value=maskPhone(d.telefone||'');populateProducts(d.produto||'');selectValue('produto',d.produto);onProductChange();selectValue('capacidade',d.capacidade);selectValue('cor',d.cor);populateConsultants(d.vendedor||'');selectValue('vendedor',d.vendedor);selectValue('preregistro',d.preregistro);selectValue('trocafone',d.trocafone);if($('wearable')){selectValue('wearable',d.wearable);$('wearable').dispatchEvent(new Event('change'));selectValue('wearableColor',d.wearableColor)}}
window.loadRecord=async function(id){if(!(await requestAdmin('editar uma pré-venda')))return;const d=getHistory().find(x=>x.id===id);if(!d)return alert('Pré-venda não encontrada. Sincronize e tente novamente.');window.preparePreSaleEdit?.();editingId=id;ensurePhone();if($('valor'))$('valor').value=d.valor||'';if($('data'))$('data').value=d.data||todayISO();if($('cliente'))$('cliente').value=d.cliente||'';if($('cpf'))$('cpf').value=d.cpf||'';if($('telefone'))$('telefone').value=maskPhone(d.telefone||'');if($('obsInterna'))$('obsInterna').value=d.obsInterna||'';restoreEditFields(d);switchTab('formPanel');window.refreshPreSaleSaveLabel?.();status('Pré-venda carregada para edição. Altere somente o que for necessário.');return d};
function editingNow(){try{return!!editingId}catch{return false}}
function selectionSnapshot(){return{editing:editingNow(),produto:$('produto')?.value||'',capacidade:$('capacidade')?.value||'',cor:$('cor')?.value||'',vendedor:$('vendedor')?.value||'',preregistro:$('preregistro')?.value||'',trocafone:$('trocafone')?.value||'',wearable:$('wearable')?.value||'',wearableColor:$('wearableColor')?.value||''}}
function restoreSelectionSnapshot(s){if(!s?.editing)return;populateProducts(s.produto);selectValue('produto',s.produto);onProductChange();selectValue('capacidade',s.capacidade);selectValue('cor',s.cor);populateConsultants(s.vendedor);selectValue('vendedor',s.vendedor);selectValue('preregistro',s.preregistro);selectValue('trocafone',s.trocafone);if($('wearable')){selectValue('wearable',s.wearable);$('wearable').dispatchEvent(new Event('change'));selectValue('wearableColor',s.wearableColor)}window.refreshPreSaleSaveLabel?.()}
const syncPreserve0=window.syncAll;window.syncAll=async function(){const snapshot=selectionSnapshot();try{return await syncPreserve0.apply(this,arguments)}finally{restoreSelectionSnapshot(snapshot)}};
const doc0=window.renderDoc;window.renderDoc=function(d){const r=doc0.apply(this,arguments);let phone=$('docTelefone');if(!phone){const cpf=$('docCpf')?.closest('.pv-row');if(cpf){const row=document.createElement('div');row.className='pv-row';row.innerHTML='<div class="pv-label">Contato</div><div class="pv-value" id="docTelefone">—</div>';cpf.insertAdjacentElement('afterend',row);phone=$('docTelefone')}}if(phone)phone.textContent=d.telefone||'—';return r};

function goals(){return parse(GOALS_KEY)||{sales:0,revenue:0,pre:0,trade:0,eco:0,consultants:{}}}
function campaign(){return parse(CAMPAIGN_KEY)||{name:'Campanha atual',closedThrough:''}}
function pending(){return new Set(parse(PENDING_KEY)||[])}
function recycle(){return parse(RECYCLE_KEY)||[]}
function recordLog(id,action,detail=''){const entry={id:crypto.randomUUID(),recordId:id,action,detail,at:new Date().toISOString(),deviceId:device()};window.persistOnlineAudit?.({...entry,action:`Pré-venda: ${action}`});const key=`record-audit-v1:${id}:${entry.id}`;dbFetch('app_settings?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{key,value:entry,updated_at:entry.at}])}).catch(console.warn)}

// Bloqueio de campanha fechada e trilha por registro.
const save0=window.saveCurrent;window.saveCurrent=async function(){const d=collect(),closed=campaign().closedThrough;if(closed&&d.data<=closed){alert(`A campanha está fechada até ${formatDateBR(closed)}. Esta pré-venda não pode ser alterada.`);return null}const before=getHistory().find(x=>x.id===d.id);const result=await save0.apply(this,arguments);if(result)recordLog(result.id,before?'editada':'criada',[result.cliente,result.produto,result.telefone].filter(Boolean).join(' • '));return result};if($('salvarBtn'))$('salvarBtn').onclick=window.saveCurrent;

// Lixeira recuperável sem alterar a tabela principal.
const delete0=window.deleteRecord;window.deleteRecord=async function(id){const d=getHistory().find(x=>x.id===id),r=await delete0.apply(this,arguments);if(d&&!getHistory().some(x=>x.id===id)){const item={record:d,deletedAt:new Date().toISOString(),deviceId:device()},rows=recycle().filter(x=>x.record?.id!==id);rows.unshift(item);save(RECYCLE_KEY,rows.slice(0,200));dbFetch('app_settings?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{key:RECYCLE_PREFIX+id,value:item,updated_at:item.deletedAt}])}).catch(console.warn);recordLog(id,'movida para a lixeira',d.cliente||'')}renderRecycle();return r};
async function restoreRecord(id){if(!(await requestAdmin('restaurar uma pré-venda')))return;const rows=recycle(),item=rows.find(x=>x.record?.id===id);if(!item)return;const deleted=parse(DELETED_KEY)||{};delete deleted[id];save(DELETED_KEY,deleted);try{await dbFetch(`app_settings?key=eq.${encodeURIComponent(DELETED_PREFIX+id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});const legacy=await getRemoteSetting('deleted_pre_sales_v1')||{};delete legacy[id];await setRemoteSetting('deleted_pre_sales_v1',legacy);item.record.updatedAt=new Date().toISOString();setHistory([item.record,...getHistory().filter(x=>x.id!==id)]);await upsertHistory([item.record]);await dbFetch(`app_settings?key=eq.${encodeURIComponent(RECYCLE_PREFIX+id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});save(RECYCLE_KEY,rows.filter(x=>x.record?.id!==id));recordLog(id,'restaurada',item.record.cliente||'');renderHistory();renderDashboard();renderRecycle();alert('Pré-venda restaurada e sincronizada.')}catch(e){console.error(e);alert('Não foi possível restaurar a pré-venda agora.') }}
window.restorePreSale=restoreRecord;

function reconciliation(){const rows=getHistory(),catalog=getCatalog(),missing=rows.filter(x=>recordValue(x)<=0),outside=rows.filter(x=>{const p=catalog.find(p=>p.name===x.produto);return!p||((p.capacities||[]).length&&!p.capacities.includes(x.capacidade))}),sum=rows.reduce((s,x)=>s+recordValue(x),0),consultants={};for(const r of rows)consultants[r.vendedor||'Não informado']=(consultants[r.vendedor||'Não informado']||0)+recordValue(r);const byConsultant=Object.values(consultants).reduce((a,b)=>a+b,0);return{rows,missing,outside,sum,consistent:Math.abs(sum-byConsultant)<.01}}
function ensureManagement(){const grid=$('settingsPanel')?.querySelector('.settings-grid');if(!grid)return;
 if(!$('reconciliationBox')){const b=document.createElement('div');b.id='reconciliationBox';b.className='settings-box management-wide';b.innerHTML='<h3>Conciliação e integridade</h3><div id="reconciliationContent"></div>';grid.appendChild(b)}
 if(!$('goalsBox')){const b=document.createElement('div');b.id='goalsBox';b.className='settings-box management-wide';b.innerHTML='<h3>Metas da campanha</h3><div class="management-form"><label>Pré-vendas<input id="goalSales" type="text" inputmode="numeric" value="0"></label><label>Faturamento<input id="goalRevenue" type="text" inputmode="decimal" value="0"></label><label>Pré-registro (%)<input id="goalPre" type="text" inputmode="decimal" value="0"></label><label>Trade-in (%)<input id="goalTrade" type="text" inputmode="decimal" value="0"></label><label>Ecossistema (%)<input id="goalEco" type="text" inputmode="decimal" value="0"></label></div><h4>Meta por consultor</h4><div class="muted-box">A meta de pré-vendas é distribuída automaticamente entre os consultores ativos.</div><div id="consultantGoals" class="consultant-goals"></div><div class="row-actions"><button id="saveGoals" class="btn">Salvar metas</button></div>';grid.appendChild(b);$('saveGoals').onclick=saveGoals}
 if(!$('campaignBox')){const b=document.createElement('div');b.id='campaignBox';b.className='settings-box';b.innerHTML='<h3>Fechamento de campanha</h3><label class="management-label">Nome da campanha<input id="campaignName"></label><label class="management-label">Fechar dados até<input id="campaignClose" type="date"></label><div class="row-actions"><button id="saveCampaign" class="btn-outline">Salvar fechamento</button><button id="openCampaign" class="btn-light">Reabrir</button><button id="newCampaign" class="btn">Nova campanha</button></div>';grid.appendChild(b);$('saveCampaign').onclick=closeCampaign;$('openCampaign').onclick=openCampaign;$('newCampaign').onclick=newCampaign}
 if(!$('recycleBox')){const b=document.createElement('div');b.id='recycleBox';b.className='settings-box';b.innerHTML='<h3>Lixeira de pré-vendas</h3><div id="recycleContent"></div>';grid.appendChild(b)}
 renderManagement();renderRecycle();renderCampaign()}
function renderManagement(){const box=$('reconciliationContent');if(!box)return;const x=reconciliation();box.innerHTML=`<div class="management-stats"><span><b>${x.rows.length}</b> registros</span><span class="${x.missing.length?'warn':'ok'}"><b>${x.missing.length}</b> sem valor</span><span class="${x.outside.length?'warn':'ok'}"><b>${x.outside.length}</b> fora do catálogo</span><span class="${x.consistent?'ok':'warn'}"><b>${x.consistent?'OK':'Atenção'}</b> cálculos</span></div>${x.missing.length?`<details><summary>Ver pendências de preço</summary>${x.missing.slice(0,30).map(r=>`<div class="management-row"><span>${esc(r.produto)} • ${esc(r.capacidade||'sem memória')}</span><small>${esc(r.vendedor||'')}</small></div>`).join('')}</details>`:''}`;const g=goals();for(const[k,id]of Object.entries({sales:'goalSales',revenue:'goalRevenue',pre:'goalPre',trade:'goalTrade',eco:'goalEco'}))if($(id))$(id).value=String(Number(g[k]||0));const cg=$('consultantGoals'),distributed=consultantGoalsFor(g.sales);if(cg)cg.innerHTML=Object.entries(distributed).map(([name,target])=>`<label>${esc(name)}<input type="text" value="${target}" readonly title="Meta calculada automaticamente"></label>`).join('')}
function goalNumber(v){return Math.max(0,Number(String(v??'').replace(',','.').replace(/[^\d.-]/g,''))||0)}function consultantGoalsFor(total){const active=getConsultants().filter(x=>x.active!==false),target=Math.max(0,Math.round(goalNumber(total))),base=active.length?Math.floor(target/active.length):0,remainder=active.length?target%active.length:0,out={};active.forEach((x,i)=>out[x.name]=base+(i<remainder?1:0));return out}async function saveGoals(){if(!(await requestAdmin('alterar as metas')))return;const sales=Math.round(goalNumber($('goalSales').value)),consultants=consultantGoalsFor(sales);const g={sales,revenue:goalNumber($('goalRevenue').value),pre:Math.min(100,goalNumber($('goalPre').value)),trade:Math.min(100,goalNumber($('goalTrade').value)),eco:Math.min(100,goalNumber($('goalEco').value)),consultants};save(GOALS_KEY,g);await setRemoteSetting('campaign_goals_v1',g);window.recordAudit?.('Metas atualizadas',campaign().name);renderDashboard();alert('Metas salvas e compartilhadas.')}
function renderCampaign(){const c=campaign();if($('campaignName'))$('campaignName').value=c.name||'';if($('campaignClose'))$('campaignClose').value=c.closedThrough||''}
async function closeCampaign(){if(!(await requestAdmin('fechar a campanha')))return;const c={name:$('campaignName').value.trim()||'Campanha',closedThrough:$('campaignClose').value};if(!c.closedThrough)return alert('Informe a data do fechamento.');if(!confirm(`Fechar alterações até ${formatDateBR(c.closedThrough)}?`))return;save(CAMPAIGN_KEY,c);await setRemoteSetting('campaign_current_v1',c);window.recordAudit?.('Campanha fechada',`${c.name} • ${c.closedThrough}`);alert('Campanha fechada. Os dados permanecem disponíveis para consulta.')}
async function openCampaign(){if(!(await requestAdmin('reabrir a campanha')))return;const c={...campaign(),closedThrough:''};save(CAMPAIGN_KEY,c);await setRemoteSetting('campaign_current_v1',c);renderCampaign();window.recordAudit?.('Campanha reaberta',c.name);alert('Campanha reaberta.')}
async function newCampaign(){if(!(await requestAdmin('iniciar uma nova campanha')))return;const name=prompt('Nome da nova campanha:');if(!name?.trim())return;const c={name:name.trim(),startedAt:todayISO(),closedThrough:''};save(CAMPAIGN_KEY,c);save(GOALS_KEY,{sales:0,revenue:0,pre:0,trade:0,eco:0,consultants:{}});await Promise.all([setRemoteSetting('campaign_current_v1',c),setRemoteSetting('campaign_goals_v1',goals())]);renderCampaign();renderManagement();renderDashboard();window.recordAudit?.('Nova campanha iniciada',c.name);alert('Nova campanha iniciada com metas zeradas. O histórico anterior foi preservado.')}
function renderRecycle(){const box=$('recycleContent');if(!box)return;const rows=recycle();box.innerHTML=rows.length?rows.slice(0,30).map(x=>`<div class="management-row"><span><b>${esc(x.record?.cliente||'Cliente')}</b><small>${esc(x.record?.produto||'')} • ${new Date(x.deletedAt).toLocaleString('pt-BR')}</small></span><button class="btn-outline" onclick="restorePreSale('${x.record.id}')">Restaurar</button></div>`).join(''):'<div class="empty">A lixeira está vazia.</div>'}

async function loadRemoteManagement(){try{const[g,c,trash]=await Promise.all([getRemoteSetting('campaign_goals_v1'),getRemoteSetting('campaign_current_v1'),dbFetch(`app_settings?key=like.${encodeURIComponent(RECYCLE_PREFIX+'%')}&select=value&order=updated_at.desc&limit=200`)]);if(g)save(GOALS_KEY,g);if(c)save(CAMPAIGN_KEY,c);const merged=[...(trash||[]).map(x=>x.value),...recycle()].filter(x=>x?.record?.id),unique=[];for(const x of merged)if(!unique.some(y=>y.record.id===x.record.id))unique.push(x);save(RECYCLE_KEY,unique);renderManagement();renderCampaign();renderRecycle();renderDashboard()}catch(e){console.warn('Configuração gerencial pendente',e)}}

function pct(value,target){return target?Math.min(999,Math.round(value/target*100)):0}
function progress(label,value,target,format=x=>x){const p=pct(value,target);return`<div class="goal-row"><span>${esc(label)}</span><b>${esc(format(value))} / ${esc(format(target))}</b><i><em style="width:${Math.min(p,100)}%"></em></i><strong>${p}%</strong></div>`}
function evolutionKey(r,group){if(group==='consultant')return r.vendedor||'Não informado';if(group==='product')return r.produto||'Não informado';if(group==='week'){const d=new Date((r.data||todayISO())+'T12:00:00'),first=new Date(d);first.setDate(d.getDate()-((d.getDay()+6)%7));return`Semana ${formatDateBR(first.toISOString().slice(0,10))}`}return formatDateBR(r.data)||'Sem data'}
function renderEvolution(rows){const box=$('managerEvolutionRows');if(!box)return;const group=$('managerEvolutionGroup')?.value||'day',metric=$('managerEvolutionMetric')?.value||'count',out={};for(const r of rows){const k=evolutionKey(r,group);out[k]=(out[k]||0)+(metric==='revenue'?recordValue(r):1)}const entries=Object.entries(out).sort((a,b)=>b[1]-a[1]).slice(0,30),max=Math.max(1,...entries.map(x=>x[1]));box.innerHTML=entries.length?entries.map(([k,v])=>`<div class="evolution-row"><span>${esc(k)}</span><i><em style="width:${Math.round(v/max*100)}%"></em></i><b>${metric==='revenue'?money(v):v}</b></div>`).join(''):'<div class="empty">Sem dados.</div>'}
function dashboardManager(){const content=$('dashCleanContent');if(!content)return;let box=$('managementDashboard');if(!box){box=document.createElement('div');box.id='managementDashboard';content.insertAdjacentElement('beforebegin',box)}const current=campaign(),raw=window.getDashboardRows?.()||getHistory(),rows=current.startedAt?raw.filter(x=>x.data>=current.startedAt):raw,g=goals(),rev=rows.reduce((s,x)=>s+recordValue(x),0),priced=rows.filter(x=>recordValue(x)>0).length,avg=priced?rev/priced:0,pre=rows.length?rows.filter(x=>x.preregistro==='SIM').length/rows.length*100:0,trade=rows.length?rows.filter(x=>x.trocafone==='SIM').length/rows.length*100:0,eco=rows.length?rows.filter(x=>x.wearable).length/rows.length*100:0,rec=reconciliation(),pendingCount=pending().size,duplicates=rows.filter((x,i,a)=>a.findIndex(y=>digits(y.cpf)===digits(x.cpf)&&y.produto===x.produto&&y.data===x.data)!==i).length,consultantCount={};for(const r of rows)consultantCount[r.vendedor||'Não informado']=(consultantCount[r.vendedor||'Não informado']||0)+1;const alerts=[rec.missing.length&&`${rec.missing.length} pré-venda(s) sem valor`,rec.outside.length&&`${rec.outside.length} registro(s) fora do catálogo`,pendingCount&&`${pendingCount} alteração(ões) aguardando envio`,duplicates&&`${duplicates} possível(is) duplicidade(s)`].filter(Boolean),consultantGoals=Object.entries(consultantGoalsFor(g.sales)).filter(x=>x[1]>0).map(([name,target])=>progress(name,consultantCount[name]||0,target)).join('');box.innerHTML=`<div class="executive-kpis"><div><span>Ticket médio</span><b>${money(avg)}</b></div><div><span>Com valor</span><b>${priced}/${rows.length}</b></div><div><span>Campanha</span><b>${esc(current.name)}</b></div></div>${alerts.length?`<div class="manager-alerts"><strong>Atenção gerencial</strong>${alerts.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<details class="goal-panel"><summary>Acompanhamento de metas</summary>${progress('Pré-vendas',rows.length,g.sales)}${progress('Faturamento',rev,g.revenue,money)}${progress('Pré-registro',Math.round(pre),g.pre,x=>x+'%')}${progress('Trade-in',Math.round(trade),g.trade,x=>x+'%')}${progress('Ecossistema',Math.round(eco),g.eco,x=>x+'%')}${consultantGoals}</details><details class="goal-panel"><summary>Evolução do desempenho</summary><div class="evolution-controls"><select id="managerEvolutionGroup"><option value="day">Por dia</option><option value="week">Por semana</option><option value="consultant">Por consultor</option><option value="product">Por produto</option></select><select id="managerEvolutionMetric"><option value="count">Quantidade</option><option value="revenue">Faturamento</option></select></div><div id="managerEvolutionRows"></div></details>`;$('managerEvolutionGroup').onchange=()=>renderEvolution(rows);$('managerEvolutionMetric').onchange=()=>renderEvolution(rows);renderEvolution(rows)}
const dash0=window.renderDashboard;window.renderDashboard=function(){const r=dash0.apply(this,arguments);dashboardManager();renderManagement();decorateHistorySoon();return r};

function decorateHistorySoon(){setTimeout(()=>{const rows=[...document.querySelectorAll('#historyContent tbody tr')],data=getHistory(),pend=pending();for(const tr of rows){const text=tr.textContent||'',d=data.find(x=>text.includes(x.cliente||'__')&&text.includes(x.produto||'__'));if(!d||tr.querySelector('.record-sync'))continue;const client=tr.children[1]||tr.children[2];if(client&&d.telefone)client.insertAdjacentHTML('beforeend',`<small class="record-phone">${esc(maskPhone(d.telefone))}</small>`);const actions=tr.querySelector('.mini-actions');if(actions){const b=document.createElement('button');b.className='btn-outline';b.textContent='Alterações';b.onclick=()=>showRecordHistory(d.id);actions.appendChild(b)}const badge=document.createElement('span');badge.className='record-sync '+(pend.has(d.id)?'pending':'ok');badge.textContent=pend.has(d.id)?'Aguardando envio':'Sincronizada';(tr.children[0]||tr).appendChild(badge)}},0)}
const history0=window.renderHistory;window.renderHistory=function(){const r=history0.apply(this,arguments);decorateHistorySoon();return r};
window.exportCSV=function(){const rows=getHistory();if(!rows.length)return alert('Não há dados.');const cols=['data','cliente','cpf','telefone','produto','capacidade','cor','vendedor','preregistro','trocafone','valor_final'],lines=[cols.join(';'),...rows.map(d=>[d.data,d.cliente,d.cpf,d.telefone,d.produto,d.capacidade,d.cor,d.vendedor,d.preregistro,d.trocafone,recordValue(d)].map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';'))],blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pre-vendas-${todayISO()}.csv`;a.click();URL.revokeObjectURL(a.href)};if($('exportarBtn'))$('exportarBtn').onclick=window.exportCSV;
async function showRecordHistory(id){try{const rows=await dbFetch(`app_settings?key=like.${encodeURIComponent('record-audit-v1:'+id+':%')}&select=value&order=updated_at.desc&limit=50`),items=(rows||[]).map(x=>x.value);const w=window.open('','_blank');if(!w)return alert('Permita a abertura de janelas.');w.document.write(`<!doctype html><meta charset="utf-8"><title>Histórico de alterações</title><style>body{font-family:Arial;padding:28px;color:#101828}h1{color:#1428A0}.item{padding:12px 0;border-bottom:1px solid #e4e7ec}small{color:#667085}</style><h1>Histórico de alterações</h1>${items.length?items.map(x=>`<div class="item"><b>${esc(x.action)}</b><br>${esc(x.detail||'')}<br><small>${new Date(x.at).toLocaleString('pt-BR')} • ${esc(x.deviceId||'')}</small></div>`).join(''):'<p>Nenhuma alteração detalhada registrada após esta atualização.</p>'}`);w.document.close()}catch(e){alert('Não foi possível consultar o histórico agora.')}}window.showRecordHistory=showRecordHistory;

// Relatório gerencial completo pronto para impressão/PDF.
window.printManagementReport=function(){const rows=window.getDashboardRows?.()||getHistory(),rev=rows.reduce((s,x)=>s+recordValue(x),0),by={};for(const r of rows){const k=r.vendedor||'Não informado';by[k]??={count:0,revenue:0};by[k].count++;by[k].revenue+=recordValue(r)}const w=window.open('','_blank');if(!w)return alert('Permita a abertura de janelas.');w.document.write(`<!doctype html><meta charset="utf-8"><title>Relatório gerencial</title><style>@page{size:A4;margin:15mm}body{font-family:Arial;color:#101828}h1{color:#1428A0}header{border-bottom:2px solid #1428A0;margin-bottom:20px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}.kpi{display:inline-block;margin-right:28px;font-size:18px}</style><header><h1>Relatório gerencial de pré-vendas</h1><p>${esc(campaign().name)} • Emitido em ${new Date().toLocaleString('pt-BR')}</p></header><p class="kpi"><b>${rows.length}</b><br>Pré-vendas</p><p class="kpi"><b>${money(rev)}</b><br>Faturamento</p><p class="kpi"><b>${money(rows.length?rev/rows.length:0)}</b><br>Ticket médio</p><h2>Resultado por consultor</h2><table><tr><th>Consultor</th><th>Pré-vendas</th><th>Faturamento</th></tr>${Object.entries(by).sort((a,b)=>b[1].revenue-a[1].revenue).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.count}</td><td>${money(v.revenue)}</td></tr>`).join('')}</table><script>window.onload=()=>window.print()<\/script>`);w.document.close();window.recordAudit?.('Relatório PDF gerado',`${rows.length} registros`)};
function addReportButton(){const toolbar=$('dashboardPanel')?.querySelector('.toolbar');if(!toolbar||$('managementReportBtn'))return;const b=document.createElement('button');b.id='managementReportBtn';b.className='btn';b.textContent='Relatório PDF';b.onclick=window.printManagementReport;toolbar.appendChild(b)}

const style=document.createElement('style');style.textContent=`.management-wide{grid-column:1/-1}.management-stats,.executive-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.management-stats span,.executive-kpis>div{padding:11px;background:#f8fafc;border-radius:10px;font-size:11px}.management-stats b,.executive-kpis b{display:block;font-size:17px;margin-top:3px}.management-stats .ok{color:#067647}.management-stats .warn{color:#b54708}.management-form{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.management-form label,.management-label,.consultant-goals label{font-size:10px;color:#667085}.management-form input,.management-label input,.consultant-goals input{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid #d0d5dd;border-radius:9px}.consultant-goals input[readonly]{background:#f2f4f7;color:#344054;font-weight:800;cursor:default}.consultant-goals{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.management-row{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid #eaecf0;font-size:11px}.management-row span small{display:block;color:#667085;margin-top:3px}.executive-kpis{grid-template-columns:repeat(3,1fr);margin-bottom:10px}.manager-alerts{display:flex;gap:8px;flex-wrap:wrap;align-items:center;padding:11px;margin-bottom:10px;background:#fffaeb;border:1px solid #fedf89;border-radius:11px;font-size:11px}.manager-alerts span{padding:5px 8px;background:#fff;border-radius:8px}.goal-panel{padding:12px;margin-bottom:12px;background:#f8fafc;border-radius:12px}.goal-panel summary{font-weight:800;cursor:pointer}.goal-row{display:grid;grid-template-columns:120px 150px 1fr 45px;gap:9px;align-items:center;margin-top:10px;font-size:11px}.goal-row>i,.evolution-row>i{height:7px;background:#e4e7ec;border-radius:999px;overflow:hidden}.goal-row>i em,.evolution-row>i em{display:block;height:100%;background:#1428A0}.evolution-controls{display:flex;gap:8px;margin:12px 0}.evolution-controls select{padding:8px;border:1px solid #d0d5dd;border-radius:9px}.evolution-row{display:grid;grid-template-columns:minmax(120px,1fr) 2fr 100px;gap:10px;align-items:center;padding:6px 0;font-size:11px}.evolution-row b{text-align:right}.record-phone{display:block;color:#1428A0;margin-top:3px}.record-sync{display:block;width:max-content;margin-top:4px;padding:3px 6px;border-radius:999px;font-size:8px}.record-sync.ok{background:#ecfdf3;color:#067647}.record-sync.pending{background:#fffaeb;color:#b54708}@media(max-width:760px){.management-stats,.executive-kpis{grid-template-columns:1fr 1fr}.management-form,.consultant-goals{grid-template-columns:1fr 1fr}.goal-row{grid-template-columns:1fr auto}.goal-row>i{grid-column:1/-1}.evolution-row{grid-template-columns:1fr auto}.evolution-row>i{display:none}}`;document.head.appendChild(style);

if($('imprimirBtn'))$('imprimirBtn').textContent='Gerar PDF';
ensureManagement();addReportButton();dashboardManager();decorateHistorySoon();loadRemoteManagement();window.refreshPreSaleSaveLabel?.();
const switch0=window.switchTab;window.switchTab=function(id){const r=switch0.apply(this,arguments);if(id==='settingsPanel'){ensureManagement();renderManagement();renderRecycle()}if(id==='dashboardPanel'){addReportButton();dashboardManager()}return r};
const footer=document.querySelector('.footer-note');if(footer)footer.textContent='PRE VENDA • v5.6.5 ONLINE';
})();
