(()=>{
'use strict';
const $=id=>document.getElementById(id);
const DEVICE_KEY='preVendaDeviceIdV1',LAST_SYNC_KEY='preVendaLastSyncV1',PENDING_KEY='preVendaPendingV1',AUTO_BACKUP_KEY='preVendaAutoBackupV1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const deviceId=(()=>{let id=localStorage.getItem(DEVICE_KEY);if(!id){id='PC-'+crypto.randomUUID().slice(0,8).toUpperCase();localStorage.setItem(DEVICE_KEY,id)}return id})();
window.professionalSyncEnabled=true;
let syncState='ready',syncError='',channel=null,coreSyncFailed=false;
try{channel=new BroadcastChannel('pre-venda-sync-v1');channel.onmessage=()=>{if(document.visibilityState==='visible'&&navigator.onLine)window.syncAll(false)}}catch{}
function pending(){try{return JSON.parse(localStorage.getItem(PENDING_KEY)||'[]')}catch{return[]}}
function setPending(ids,add){const s=new Set(pending());for(const id of ids||[]){if(!id)continue;add?s.add(id):s.delete(id)}localStorage.setItem(PENDING_KEY,JSON.stringify([...s]));renderSyncCenter()}
function syncLabel(){if(!navigator.onLine)return['offline','Sem conexão'];if(syncState==='syncing')return['busy','Sincronizando'];if(syncState==='error')return['error','Falha na sincronização'];return['ok','Sincronizado']}
function ensureSyncCenter(){const grid=$('settingsPanel')?.querySelector('.settings-grid');if(!grid)return;let box=$('professionalSyncBox');if(box)return;box=document.createElement('div');box.id='professionalSyncBox';box.className='settings-box sync-center-box';box.innerHTML='<h3>Central de sincronização</h3><div id="professionalSyncState"></div><div class="sync-center-grid"><div><span>Última sincronização</span><strong id="professionalLastSync">—</strong></div><div><span>Alterações pendentes</span><strong id="professionalPending">0</strong></div><div><span>Computador</span><strong id="professionalDevice"></strong></div><div><span>Atualização automática</span><strong>A cada 20 segundos</strong></div></div><div id="professionalSyncError" class="sync-center-error"></div><div class="row-actions"><button class="btn" id="professionalSyncNow">Sincronizar agora</button><button class="btn-outline" id="professionalRestoreAuto">Restaurar último backup</button></div>';grid.prepend(box);$('professionalSyncNow').onclick=()=>window.syncAll(true);$('professionalRestoreAuto').onclick=restoreAutoBackup;renderSyncCenter()}
function renderSyncCenter(){ensureSyncCenter();const state=$('professionalSyncState');if(!state)return;const[cls,label]=syncLabel();state.innerHTML=`<div class="sync-center-status ${cls}"><i></i><strong>${label}</strong></div>`;$('professionalLastSync').textContent=localStorage.getItem(LAST_SYNC_KEY)?new Date(localStorage.getItem(LAST_SYNC_KEY)).toLocaleString('pt-BR'):'Ainda não concluída';$('professionalPending').textContent=String(pending().length);$('professionalDevice').textContent=deviceId;$('professionalSyncError').textContent=syncError}
function storedBackup(){try{return JSON.parse(localStorage.getItem(AUTO_BACKUP_KEY)||'null')}catch{return null}}
function autoBackup(){const now=new Date(),last=storedBackup();if(last?.day===todayISO())return;const payload={day:todayISO(),at:now.toISOString(),history:getHistory(),catalog:getCatalog(),consultants:getConsultants()};localStorage.setItem(AUTO_BACKUP_KEY,JSON.stringify(payload))}
async function restoreAutoBackup(){if(!(await requestAdmin('restaurar o backup automático')))return;const data=storedBackup();if(!data?.history)return alert('Nenhum backup automático disponível neste computador.');if(!confirm(`Restaurar o backup de ${new Date(data.at).toLocaleString('pt-BR')}?`))return;setHistory(mergeHistory(getHistory(),data.history));await saveCatalog(data.catalog||getCatalog());await saveConsultants(data.consultants||getConsultants());await window.syncAll(false);renderHistory();renderDashboard();alert('Backup automático restaurado com sucesso.')}

const upsert0=window.upsertHistory;window.upsertHistory=async function(items){const ids=(items||[]).map(x=>x.id).filter(Boolean);setPending(ids,true);try{const r=await upsert0.apply(this,arguments);setPending(ids,false);return r}catch(err){syncState='error';syncError='Existem alterações aguardando envio.';renderSyncCenter();throw err}};
const onlineState0=window.setOnlineState;window.setOnlineState=function(state,label){if(state==='off'){coreSyncFailed=true;syncState='error';syncError=label||'Não foi possível concluir a sincronização.'}return onlineState0.apply(this,arguments)};
const sync0=window.syncAll;window.syncAll=async function(show=true){if(syncState==='syncing')return;syncState='syncing';syncError='';coreSyncFailed=false;renderSyncCenter();try{const r=await sync0.apply(this,arguments);if(coreSyncFailed)return r;localStorage.setItem(LAST_SYNC_KEY,new Date().toISOString());syncState='ready';autoBackup();channel?.postMessage({type:'updated',at:Date.now()});return r}catch(err){syncState='error';syncError=err?.message||'Não foi possível concluir a sincronização.';throw err}finally{renderSyncCenter()}};

window.persistOnlineAudit=async entry=>{try{await dbFetch('app_settings?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{key:'audit-v1:'+entry.id,value:{...entry,deviceId},updated_at:entry.at}])})}catch(err){console.warn('Auditoria online pendente',err)}};
async function renderOnlineAudit(){const box=$('auditList');if(!box||!navigator.onLine)return;try{const rows=await dbFetch('app_settings?key=like.'+encodeURIComponent('audit-v1:%')+'&select=value&order=updated_at.desc&limit=100'),items=(rows||[]).map(x=>x.value).filter(Boolean);if(items.length)box.innerHTML=items.map(x=>`<div class="audit-item"><strong>${esc(x.action)}</strong>${esc(new Date(x.at).toLocaleString('pt-BR'))}<br><small>${esc(x.deviceId||'Computador não identificado')}</small>${x.detail?`<br>${esc(x.detail)}`:''}</div>`).join('')}catch(err){console.warn(err)}}

function addPriceButtons(){document.querySelectorAll('#catalogList .catalog-item').forEach(item=>{if(item.querySelector('.price-edit-btn'))return;const edit=item.querySelector('[onclick^="editProduct"]'),m=edit?.getAttribute('onclick')?.match(/editProduct\('([^']+)'\)/);if(!m)return;const b=document.createElement('button');b.className='btn-outline price-edit-btn';b.textContent='Valores';b.onclick=()=>editProductPrices(m[1]);item.querySelector('.catalog-actions')?.prepend(b)})}
window.editProductPrices=async function(id){if(!(await requestAdmin('editar os valores finais')))return;const cat=getCatalog(),p=cat.find(x=>x.id===id);if(!p)return;const from=prompt('A partir de qual data estes valores serão válidos? (AAAA-MM-DD)',todayISO());if(from===null)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(from))return alert('Informe a data no formato AAAA-MM-DD.');const keys=(p.capacities||[]).length?p.capacities:['_default'];p.finalPrices=p.finalPrices||{};p.priceHistory=p.priceHistory||{};let changed=false;for(const key of keys){const label=key==='_default'?'produto sem memória':key,current=p.finalPrices[key]||'';const raw=prompt(`Valor final para ${label} (somente números). Deixe vazio para não cadastrar.`,current);if(raw===null)return;const value=Number(String(raw).replace(/[^\d,.-]/g,'').replace(/\./g,'').replace(',','.'));if(!raw.trim())continue;if(!Number.isFinite(value)||value<=0)return alert('Informe um valor válido.');p.finalPrices[key]=value;p.priceHistory[key]=Array.isArray(p.priceHistory[key])?p.priceHistory[key]:[];p.priceHistory[key]=p.priceHistory[key].filter(x=>x.from!==from);p.priceHistory[key].push({from,value});p.priceHistory[key].sort((a,b)=>String(a.from).localeCompare(String(b.from)));changed=true}if(changed){await saveCatalog(cat);window.recordAudit?.('Valores finais alterados',`${p.name} • vigência ${from}`);renderCatalog()}};
const renderCatalog0=window.renderCatalog;window.renderCatalog=function(){const r=renderCatalog0.apply(this,arguments);setTimeout(addPriceButtons,0);return r};

function dateISO(d){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function setPeriod(kind){const end=new Date(),start=new Date(end);if(kind==='all'){$('dashStart').value='';$('dashEnd').value=''}else{if(kind==='today'){}else if(kind==='week')start.setDate(end.getDate()-6);else if(kind==='month')start.setDate(1);$('dashStart').value=dateISO(start);$('dashEnd').value=dateISO(end)}renderDashboard()}
function ensureQuickPeriods(){const toolbar=$('dashboardPanel')?.querySelector('.toolbar');if(!toolbar||$('dashQuickPeriods'))return;const box=document.createElement('div');box.id='dashQuickPeriods';box.className='dash-quick-periods';box.innerHTML='<button data-period="today">Hoje</button><button data-period="week">7 dias</button><button data-period="month">Este mês</button><button data-period="all" class="active">Todo histórico</button>';toolbar.insertAdjacentElement('beforebegin',box);box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));setPeriod(b.dataset.period)})}
function dashboardRows(){return typeof window.getDashboardRows==='function'?window.getDashboardRows():getHistory()}
function reportCSV(){const rows=dashboardRows();if(!rows.length)return alert('Não há dados no período.');const cols=['data','cliente','produto','capacidade','cor','consultor','valor_final','pre_registro','trade_in','ecossistema'],lines=[cols.join(';'),...rows.map(d=>[d.data,d.cliente,d.produto,d.capacidade,d.cor,d.vendedor,window.getPreSaleFinalValue?.(d)||0,d.preregistro,d.trocafone,d.wearable].map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';'))],blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`relatorio-pre-vendas-${todayISO()}.csv`;a.click();URL.revokeObjectURL(a.href);window.recordAudit?.('Relatório gerencial exportado',`${rows.length} registros`)}
function printReport(){const rows=dashboardRows(),total=rows.reduce((s,x)=>s+Number(window.getPreSaleFinalValue?.(x)||0),0),by={};for(const r of rows){const k=r.vendedor||'Não informado';by[k]=(by[k]||0)+Number(window.getPreSaleFinalValue?.(r)||0)}const w=window.open('','_blank');if(!w)return alert('Permita a abertura de janelas para imprimir o relatório.');w.document.write(`<!doctype html><meta charset="utf-8"><title>Relatório de pré-vendas</title><style>body{font-family:Arial;padding:32px;color:#101828}h1{color:#1428A0}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}.total{font-size:24px;font-weight:bold}</style><h1>Relatório de pré-vendas</h1><p>${rows.length} pré-vendas no período</p><p class="total">Faturamento: ${money(total)}</p><table><thead><tr><th>Consultor</th><th>Faturamento</th></tr></thead><tbody>${Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${money(v)}</td></tr>`).join('')}</tbody></table><script>window.onload=()=>window.print()<\/script>`);w.document.close()}
function ensureReportButtons(){const toolbar=$('dashboardPanel')?.querySelector('.toolbar');if(!toolbar||$('dashReportCsv'))return;const csv=document.createElement('button');csv.id='dashReportCsv';csv.className='btn-outline';csv.textContent='Exportar relatório';csv.onclick=reportCSV;const print=document.createElement('button');print.id='dashPrintReport';print.className='btn-outline';print.textContent='Imprimir resumo';print.onclick=printReport;toolbar.append(csv,print)}
function renderComparison(){const root=$('dashCleanRoot'),content=$('dashCleanContent'),s=$('dashStart')?.value,e=$('dashEnd')?.value;if(!root||!content)return;root.querySelector('#dashPeriodComparison')?.remove();if(!s||!e||s>e)return;const start=new Date(s+'T12:00:00'),end=new Date(e+'T12:00:00'),days=Math.round((end-start)/86400000)+1,prevEnd=new Date(start);prevEnd.setDate(prevEnd.getDate()-1);const prevStart=new Date(prevEnd);prevStart.setDate(prevStart.getDate()-days+1);const filters=window.getDashboardFilterState?.()||{},products=new Set(filters.products||[]),previous=getHistory().filter(x=>x.data>=dateISO(prevStart)&&x.data<=dateISO(prevEnd)&&(!filters.consultant||x.vendedor===filters.consultant)&&(!products.size||products.has(x.produto))),current=dashboardRows(),pv=x=>x.reduce((sum,r)=>sum+Number(window.getPreSaleFinalValue?.(r)||0),0),curRevenue=pv(current),prevRevenue=pv(previous),pct=(a,b)=>b?Math.round((a-b)/b*100):a?100:0;const box=document.createElement('div');box.id='dashPeriodComparison';box.className='dash-period-comparison';box.innerHTML=`<strong>Comparação com o período anterior</strong><span>Pré-vendas: <b>${current.length}</b> <i class="${pct(current.length,previous.length)>=0?'up':'down'}">${pct(current.length,previous.length)>=0?'+':''}${pct(current.length,previous.length)}%</i></span><span>Faturamento: <b>${money(curRevenue)}</b> <i class="${pct(curRevenue,prevRevenue)>=0?'up':'down'}">${pct(curRevenue,prevRevenue)>=0?'+':''}${pct(curRevenue,prevRevenue)}%</i></span>`;content.prepend(box)}
const renderDashboard0=window.renderDashboard;window.renderDashboard=function(){const r=renderDashboard0.apply(this,arguments);ensureQuickPeriods();ensureReportButtons();renderComparison();return r};

function updateNotice(){if($('appUpdateNotice'))return;const n=document.createElement('div');n.id='appUpdateNotice';n.className='app-update-notice';n.innerHTML='<span>Uma nova versão está disponível.</span><button>Atualizar agora</button>';n.querySelector('button').onclick=()=>location.reload();document.body.appendChild(n)}
if('serviceWorker'in navigator)navigator.serviceWorker.getRegistration().then(reg=>{reg?.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)updateNotice()})})});

const style=document.createElement('style');style.textContent=`.sync-center-box{grid-column:1/-1}.sync-center-status{display:flex;align-items:center;gap:8px;margin:8px 0 14px}.sync-center-status i{width:10px;height:10px;border-radius:50%;background:#98a2b3}.sync-center-status.ok i{background:#12b76a}.sync-center-status.busy i{background:#f79009}.sync-center-status.error i,.sync-center-status.offline i{background:#f04438}.sync-center-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.sync-center-grid>div{padding:11px;background:#f8fafc;border-radius:10px}.sync-center-grid span{display:block;font-size:10px;color:#667085}.sync-center-grid strong{display:block;margin-top:4px;font-size:12px}.sync-center-error{color:#b42318;font-size:11px;margin-top:8px}.dash-quick-periods{display:flex;gap:6px;margin-bottom:10px;flex-wrap:wrap}.dash-quick-periods button{padding:7px 10px;background:#eef2f6;color:#475467}.dash-quick-periods button.active{background:#1428A0;color:#fff}.dash-period-comparison{display:flex;gap:18px;align-items:center;padding:11px 13px;margin-bottom:12px;background:#f8fafc;border-radius:12px;font-size:11px}.dash-period-comparison>strong{margin-right:auto}.dash-period-comparison span{white-space:nowrap}.dash-period-comparison i{font-style:normal;font-weight:800;margin-left:4px}.dash-period-comparison .up{color:#067647}.dash-period-comparison .down{color:#b42318}.app-update-notice{position:fixed;z-index:500;right:18px;bottom:18px;display:flex;align-items:center;gap:12px;padding:12px 14px;background:#101828;color:#fff;border-radius:12px;box-shadow:0 12px 30px rgba(0,0,0,.25)}.app-update-notice button{padding:7px 10px;background:#fff;color:#1428A0}@media(max-width:760px){.sync-center-grid{grid-template-columns:1fr 1fr}.dash-period-comparison{align-items:flex-start;flex-direction:column;gap:6px}.dash-period-comparison>strong{margin:0}.app-update-notice{left:10px;right:10px;bottom:70px;justify-content:space-between}}`;document.head.appendChild(style);

ensureSyncCenter();ensureQuickPeriods();ensureReportButtons();renderCatalog();renderDashboard();autoBackup();renderOnlineAudit();
setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine&&syncState!=='syncing')window.syncAll(false)},20000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){window.syncAll(false);renderOnlineAudit()}});
const switch0=window.switchTab;window.switchTab=function(id){const r=switch0.apply(this,arguments);if(id==='settingsPanel'){ensureSyncCenter();renderOnlineAudit()}return r};
const f=document.querySelector('.footer-note');if(f)f.textContent='PRE VENDA • v5.4.0 ONLINE';
})();
