(()=>{
'use strict';
const byId=id=>document.getElementById(id);
const STATUS_VALUES=['Aguardando produto','Cliente avisado','Retirado'];
const AUDIT_KEY='preVendaAuditLog';
let historyPage=1; const PAGE_SIZE=20;
const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const norm=v=>String(v??'').trim();
const statusClass=s=>s==='Retirado'?'status-retirado':s==='Cliente avisado'?'status-avisado':'status-aguardando';
function extractMarker(text,key){const m=String(text||'').match(new RegExp('\\[\\['+key+':(.*?)\\]\\]'));return m?m[1]:''}
function cleanMarker(text,key){return String(text||'').replace(new RegExp('\\n?\\[\\['+key+':.*?\\]\\]','g'),'').trim()}
function appendMarker(text,key,val){const c=cleanMarker(text,key);return c+(val?'\n[['+key+':'+val+']]':'')}
function getAudit(){try{return JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]')}catch{return[]}}
function audit(action,detail=''){const list=getAudit();list.unshift({at:new Date().toISOString(),action,detail});localStorage.setItem(AUDIT_KEY,JSON.stringify(list.slice(0,200)));renderAudit()}
function renderAudit(){const box=byId('auditList');if(!box)return;const rows=getAudit();box.innerHTML=rows.length?rows.slice(0,100).map(x=>`<div class="audit-item"><strong>${esc(x.action)}</strong>${esc(new Date(x.at).toLocaleString('pt-BR'))}${x.detail?`<br>${esc(x.detail)}`:''}</div>`).join(''):'<div class="empty">Nenhuma alteração registrada neste aparelho.</div>'}

function ensureStatusField(){byId('saleStatus')?.closest('.field')?.remove()}
function ensureHistoryFilters(){const card=byId('historyPanel')?.querySelector('.card');if(!card||byId('histStatus'))return;const toolbar=card.querySelector('.toolbar');const f=document.createElement('div');f.className='history-filters';f.innerHTML='<input id="histStart" type="date" title="Data inicial"><input id="histEnd" type="date" title="Data final"><select id="histConsultant"><option value="">Todos os consultores</option></select><select id="histProduct"><option value="">Todos os produtos</option></select><select id="histStatus"><option value="">Todos os status</option>'+STATUS_VALUES.map(x=>`<option>${x}</option>`).join('')+'</select><select id="histEco"><option value="">Com ou sem Ecossistema</option><option value="com">Com Ecossistema</option><option value="sem">Sem Ecossistema</option></select>';
toolbar.insertAdjacentElement('afterend',f);['histStart','histEnd','histConsultant','histProduct','histStatus','histEco'].forEach(id=>byId(id).addEventListener('change',()=>{historyPage=1;renderHistory()}));}
function ensureSettingsEnhancements(){const grid=byId('settingsPanel')?.querySelector('.settings-grid');if(!grid||byId('backupBox'))return;const b=document.createElement('div');b.className='settings-box';b.id='backupBox';b.innerHTML='<h3>Backup e recuperação</h3><div class="muted-box">Exporte uma cópia completa do histórico, catálogo e consultores. O arquivo pode ser restaurado neste ou em outro aparelho.</div><div class="row-actions backup-actions"><button class="btn-outline" id="exportBackupBtn">Exportar backup</button><label class="btn-outline" style="cursor:pointer">Restaurar backup<input id="importBackupFile" type="file" accept="application/json" style="display:none"></label></div>';grid.appendChild(b);const a=document.createElement('div');a.className='settings-box';a.innerHTML='<h3>Auditoria local</h3><div class="muted-box">Registra ações administrativas realizadas neste aparelho.</div><div id="auditList" class="audit-list"></div><div class="row-actions"><button class="btn-outline" id="clearAuditBtn">Limpar auditoria</button></div>';grid.appendChild(a);byId('exportBackupBtn').onclick=exportBackup;byId('importBackupFile').onchange=importBackup;byId('clearAuditBtn').onclick=async()=>{if(!(await requestAdmin('limpar a auditoria')))return;localStorage.removeItem(AUDIT_KEY);renderAudit()};renderAudit()}
function ensureMobileNav(){if(document.querySelector('.mobile-bottom-nav'))return;const nav=document.createElement('div');nav.className='mobile-bottom-nav screen-only';nav.innerHTML='<button data-v5tab="homePanel">Início</button><button data-v5tab="formPanel">Nova</button><button data-v5tab="historyPanel">Histórico</button><button data-v5tab="dashboardPanel">Dashboard</button>';document.body.appendChild(nav);nav.querySelectorAll('button').forEach(b=>b.onclick=()=>switchTab(b.dataset.v5tab));const tabs=document.querySelector('.tabs');if(tabs&&!document.querySelector('.mobile-menu-toggle')){const m=document.createElement('button');m.className='mobile-menu-toggle';m.textContent='☰ Menu';m.onclick=()=>tabs.classList.toggle('menu-open');tabs.appendChild(m)}}

const collect0=window.collect;window.collect=function(){const d=collect0(),current=editingId?getHistory().find(x=>x.id===editingId):null;d.statusVenda=current?.statusVenda||'Aguardando produto';return d};
const validate0=window.validate;window.validate=function(d){return validate0(d)};
const toDb0=window.toDb;window.toDb=function(d){const r=toDb0(d);r.obs_interna=appendMarker(r.obs_interna,'STATUS',d.statusVenda||'Aguardando produto');return r};
const fromDb0=window.fromDb;window.fromDb=function(r){const d=fromDb0(r);d.statusVenda=extractMarker(r.obs_interna,'STATUS')||'Aguardando produto';d.obsInterna=cleanMarker(d.obsInterna,'STATUS');return d};
const clear0=window.clearForm;window.clearForm=function(){clear0();ensureStatusField()};
const load0=window.loadRecord;window.loadRecord=async function(id){await load0(id);ensureStatusField()};
const save0=window.saveCurrent;window.saveCurrent=async function(){const before=editingId;const d=await save0();if(d)audit(before?'Pré-venda editada':'Pré-venda criada',[d.cliente,d.produto,d.statusVenda].filter(Boolean).join(' • '));return d};
const del0=window.deleteRecord;window.deleteRecord=async function(id){const d=getHistory().find(x=>x.id===id);const before=getHistory().length;await del0(id);if(getHistory().length<before)audit('Pré-venda excluída',[d?.cliente,d?.produto].filter(Boolean).join(' • '))};
const cat0=window.saveCatalog;window.saveCatalog=async function(x){await cat0(x);audit('Catálogo alterado',`${x.length} produtos cadastrados`)};
const cons0=window.saveConsultants;window.saveConsultants=async function(x){await cons0(x);audit('Consultores alterados',`${x.length} consultores cadastrados`)};

window.setSaleStatus=async function(id,status){if(!(await requestAdmin('alterar o status da pré-venda')))return;const h=getHistory(),d=h.find(x=>x.id===id);if(!d)return;d.statusVenda=status;d.updatedAt=new Date().toISOString();setHistory(h);try{await upsertHistory([d]);setOnlineState('ok','Online')}catch(e){console.error(e);setOnlineState('off','Sync pendente')}audit('Status alterado',`${d.cliente||''} • ${status}`);renderHistory();renderDashboard()};
function filteredHistory(){const q=byId('busca')?.value.trim().toLowerCase()||'',s=byId('histStart')?.value||'',e=byId('histEnd')?.value||'',c=byId('histConsultant')?.value||'',p=byId('histProduct')?.value||'',st=byId('histStatus')?.value||'',eco=byId('histEco')?.value||'';return getHistory().filter(d=>(!q||[d.cliente,d.cpf,d.produto,d.capacidade,d.cor,d.wearable,d.wearableColor,d.vendedor,d.statusVenda].some(v=>String(v||'').toLowerCase().includes(q)))&&(!s||d.data>=s)&&(!e||d.data<=e)&&(!c||d.vendedor===c)&&(!p||d.produto===p)&&(!st||(d.statusVenda||'Aguardando produto')===st)&&(!eco||(eco==='com'?!!d.wearable:!d.wearable)))}
window.renderHistory=function(){ensureHistoryFilters();updateMetrics();const all=getHistory(),consultants=[...new Set(all.map(x=>x.vendedor).filter(Boolean))].sort(),products=[...new Set(all.map(x=>x.produto).filter(Boolean))].sort();const c=byId('histConsultant').value,p=byId('histProduct').value;byId('histConsultant').innerHTML='<option value="">Todos os consultores</option>'+consultants.map(x=>`<option>${esc(x)}</option>`).join('');byId('histProduct').innerHTML='<option value="">Todos os produtos</option>'+products.map(x=>`<option>${esc(x)}</option>`).join('');if(consultants.includes(c))byId('histConsultant').value=c;if(products.includes(p))byId('histProduct').value=p;const rows=filteredHistory(),pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));historyPage=Math.min(historyPage,pages);const pageRows=rows.slice((historyPage-1)*PAGE_SIZE,historyPage*PAGE_SIZE);if(!rows.length){byId('historyContent').innerHTML='<div class="empty">Nenhuma pré-venda encontrada.</div>';return}byId('historyContent').innerHTML=`<div class="history-meta"><strong>${rows.length}</strong> resultado(s) • Página ${historyPage} de ${pages}</div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Produto</th><th>Ecossistema</th><th>Consultor</th><th>Status</th><th>Ações</th></tr></thead><tbody>${pageRows.map(d=>`<tr><td>${formatDateBR(d.data)}</td><td>${esc(d.cliente||'')}<br><small>${esc(maskedCpf(d.cpf||''))}</small></td><td>${esc([d.produto,/^não se aplica$/i.test(d.capacidade||'')?'':d.capacidade,d.cor].filter(Boolean).join(' • '))}</td><td>${d.wearable?esc(d.wearable+(d.wearableColor?' • '+d.wearableColor:'')):'—'}</td><td>${esc(d.vendedor||'')}</td><td><select onchange="setSaleStatus('${d.id}',this.value)" class="status-badge ${statusClass(d.statusVenda||'Aguardando produto')}">${STATUS_VALUES.map(x=>`<option ${x===(d.statusVenda||'Aguardando produto')?'selected':''}>${x}</option>`).join('')}</select></td><td><div class="mini-actions"><button class="btn-outline" onclick="printRecord('${d.id}')">Imprimir</button><button class="btn-outline" onclick="loadRecord('${d.id}')">Editar</button><button class="btn-danger" onclick="deleteRecord('${d.id}')">Excluir</button></div></td></tr>`).join('')}</tbody></table></div>${pages>1?`<div class="row-actions"><button class="btn-outline" onclick="window.v5Page(-1)" ${historyPage===1?'disabled':''}>Anterior</button><button class="btn-outline" onclick="window.v5Page(1)" ${historyPage===pages?'disabled':''}>Próxima</button></div>`:''}`};window.v5Page=delta=>{historyPage+=delta;renderHistory()};

const dash0=window.renderDashboard;window.renderDashboard=function(){dash0();const s=byId('dashStart').value,e=byId('dashEnd').value,c=byId('dashConsultant').value,data=getHistory().filter(x=>(!s||x.data>=s)&&(!e||x.data<=e)&&(!c||x.vendedor===c));let eco=data.filter(x=>x.wearable).length,ret=data.filter(x=>(x.statusVenda||'Aguardando produto')==='Retirado').length,avis=data.filter(x=>x.statusVenda==='Cliente avisado').length;let extra=byId('dashV5');if(!extra){extra=document.createElement('div');extra.id='dashV5';extra.className='dashboard-grid';byId('dashboardPanel').querySelector('.dashboard-grid').insertAdjacentElement('afterend',extra)}extra.innerHTML=`<div class="dash-card"><span>Com Ecossistema</span><strong>${eco}</strong></div><div class="dash-card"><span>Taxa de Ecossistema</span><strong>${data.length?Math.round(eco/data.length*100):0}%</strong></div><div class="dash-card"><span>Clientes avisados</span><strong>${avis}</strong></div><div class="dash-card"><span>Retirados</span><strong>${ret}</strong></div>`;let sec=byId('dashEcoModels');if(!sec){sec=document.createElement('div');sec.className='dash-section';sec.innerHTML='<h3>Ecossistema por modelo</h3><div id="dashEcoModels"></div>';byId('dashboardPanel').querySelector('.card').appendChild(sec)}const g={};data.filter(x=>x.wearable).forEach(x=>g[x.wearable]=(g[x.wearable]||0)+1);renderBars('dashEcoModels',g)};

const renderCat0=window.renderCatalog;window.renderCatalog=function(){renderCat0();const box=byId('catalogList');if(!box)return;const items=[...box.children],cat=getCatalog();if(!items.length)return;box.innerHTML='';const zTitle=document.createElement('div');zTitle.className='settings-group-title';zTitle.textContent='Galaxy Z';box.appendChild(zTitle);cat.forEach((p,i)=>{if(/galaxy\s*z\s*(flip|fold)/i.test(p.name))box.appendChild(items[i])});const eTitle=document.createElement('div');eTitle.className='settings-group-title';eTitle.textContent='Ecossistema';box.appendChild(eTitle);cat.forEach((p,i)=>{if(/galaxy\s*(watch|buds|ring|fit)/i.test(p.name))box.appendChild(items[i])});const o=cat.map((p,i)=>({p,i})).filter(x=>!/galaxy\s*z\s*(flip|fold)/i.test(x.p.name)&&!/galaxy\s*(watch|buds|ring|fit)/i.test(x.p.name));if(o.length){const t=document.createElement('div');t.className='settings-group-title';t.textContent='Outros';box.appendChild(t);o.forEach(x=>box.appendChild(items[x.i]))}};

function exportBackup(){const payload={version:'5.0',exportedAt:new Date().toISOString(),history:getHistory(),catalog:getCatalog(),consultants:getConsultants(),audit:getAudit()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pre-venda-backup-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href);audit('Backup exportado')}
async function importBackup(e){if(!(await requestAdmin('restaurar um backup')))return;const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.history)||!Array.isArray(data.catalog)||!Array.isArray(data.consultants))throw new Error('Arquivo incompatível');const merged=mergeHistory(getHistory(),data.history);setHistory(merged);await saveCatalog(data.catalog);await saveConsultants(data.consultants);if(Array.isArray(data.audit))localStorage.setItem(AUDIT_KEY,JSON.stringify(data.audit.slice(0,200)));await syncAll(false);audit('Backup restaurado',`${merged.length} pré-vendas`);renderHistory();renderDashboard();alert('Backup restaurado com sucesso.')}catch(err){alert('Não foi possível restaurar o backup: '+err.message)}finally{e.target.value=''}}

ensureStatusField();ensureHistoryFilters();ensureSettingsEnhancements();ensureMobileNav();
const search=byId('busca');if(search)search.oninput=()=>{historyPage=1;renderHistory()};
const switch0=window.switchTab;window.switchTab=function(id){switch0(id);document.querySelectorAll('.mobile-bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.v5tab===id));if(id==='historyPanel')renderHistory();if(id==='dashboardPanel')renderDashboard();if(id==='settingsPanel'){ensureSettingsEnhancements();renderCatalog();renderAudit()}};
clearForm();renderHistory();renderDashboard();renderCatalog();
const footer=document.querySelector('.footer-note');if(footer)footer.textContent='PRE VENDA • v5.0';
})();
