(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const fmt=v=>{if(!v)return'—';try{return new Date(v).toLocaleString('pt-BR')}catch{return'—'}};
function ensurePanel(){if($('withdrawalsPanel'))return;const dash=$('dashboardPanel');if(!dash)return;const panel=document.createElement('section');panel.id='withdrawalsPanel';panel.className='panel screen-only';panel.innerHTML='<div class="card"><div class="section-title">Retiradas</div><div class="withdrawals-toolbar"><input id="withdrawalSearch" placeholder="Buscar cliente, produto ou consultor"><select id="withdrawalStatus"><option value="">Pendentes e avisados</option><option>Aguardando produto</option><option>Cliente avisado</option><option>Retirado</option></select></div><div id="withdrawalContent"></div></div>';dash.insertAdjacentElement('afterend',panel);const btn=document.createElement('button');btn.className='tab-btn btn-light';btn.dataset.tab='withdrawalsPanel';btn.textContent='Retiradas';document.querySelector('.tab-btn[data-tab="settingsPanel"]')?.insertAdjacentElement('beforebegin',btn);btn.onclick=()=>{switchTab('withdrawalsPanel');renderWithdrawals()};$('withdrawalSearch').oninput=renderWithdrawals;$('withdrawalStatus').onchange=renderWithdrawals}
window.renderWithdrawals=function(){ensurePanel();const box=$('withdrawalContent');if(!box)return;const q=($('withdrawalSearch')?.value||'').toLowerCase(),st=$('withdrawalStatus')?.value||'';const data=getHistory().filter(d=>{const s=d.statusVenda||'Aguardando produto';if(st){if(s!==st)return false}else if(s==='Retirado')return false;return !q||[d.cliente,d.produto,d.vendedor,d.wearable].some(v=>String(v||'').toLowerCase().includes(q))});if(!data.length){box.innerHTML='<div class="empty">Nenhuma retirada encontrada.</div>';return}box.innerHTML='<div class="withdrawal-grid">'+data.map(d=>`<div class="withdrawal-card"><strong>${esc(d.cliente||'Cliente')}</strong><small>${esc([d.produto,d.capacidade,d.cor].filter(Boolean).join(' • '))}</small>${d.wearable?`<small>Ecossistema: ${esc(d.wearable+(d.wearableColor?' • '+d.wearableColor:''))}</small>`:''}<small>Consultor: ${esc(d.vendedor||'—')}</small><div class="timeline"><div class="timeline-item"><strong>Última atualização:</strong> ${fmt(d.updatedAt)}</div></div><div class="row-actions"><button class="btn-outline" onclick="printRecord('${d.id}')">Imprimir</button>${sButton(d)}</div></div>`).join('')+'</div>'};
function sButton(d){const s=d.statusVenda||'Aguardando produto';if(s==='Aguardando produto')return `<button class="btn" onclick="setSaleStatus('${d.id}','Cliente avisado')">Marcar avisado</button>`;if(s==='Cliente avisado')return `<button class="btn" onclick="setSaleStatus('${d.id}','Retirado')">Marcar retirado</button>`;return''}
function onlineBanner(){let b=$('onlineBanner');if(!b){b=document.createElement('div');b.id='onlineBanner';document.querySelector('.content')?.prepend(b)}const online=navigator.onLine!==false;b.className='online-banner'+(online?'':' off');b.innerHTML=`<div><strong>${online?'Base online ativa':'Modo offline'}</strong><span>${online?'Histórico e dashboard compartilhados entre os aparelhos.':'Os dados locais permanecem disponíveis até a conexão voltar.'}</span></div>`}
const h0=window.renderHistory;window.renderHistory=function(){h0();renderWithdrawals()};const d0=window.renderDashboard;window.renderDashboard=function(){d0();const s=$('dashStart')?.value||'',e=$('dashEnd')?.value||'',c=$('dashConsultant')?.value||'',data=getHistory().filter(x=>(!s||x.data>=s)&&(!e||x.data<=e)&&(!c||x.vendedor===c)),open=data.filter(x=>(x.statusVenda||'Aguardando produto')!=='Retirado').length,ret=data.filter(x=>x.statusVenda==='Retirado').length;let n=$('dashOpsV51');if(!n){n=document.createElement('div');n.id='dashOpsV51';n.className='dashboard-grid';($('dashV5')||$('dashboardPanel')?.querySelector('.dashboard-grid'))?.insertAdjacentElement('afterend',n)}if(n)n.innerHTML=`<div class="dash-card"><span>Em aberto</span><strong>${open}</strong></div><div class="dash-card"><span>Taxa de retirada</span><strong>${data.length?Math.round(ret/data.length*100):0}%</strong></div>`};
ensurePanel();onlineBanner();renderWithdrawals();renderDashboard();window.addEventListener('online',()=>{onlineBanner();syncAll(false)});window.addEventListener('offline',onlineBanner);setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine&&!syncBusy)pullHistory().then(()=>{renderHistory();renderDashboard()}).catch(()=>{})},30000);const f=document.querySelector('.footer-note');if(f)f.textContent='PRE VENDA • v5.1 ONLINE';
})();