(()=>{
'use strict';
const RELEASE='7.4.1',STABLE_BASE='7.4.0',CACHE_EPOCH='v7-4-1-verified-deploy';
window.PRE_SALE_RELEASE=RELEASE;window.PRE_SALE_STABLE_BASE=STABLE_BASE;window.PRE_SALE_CACHE_EPOCH=CACHE_EPOCH;document.documentElement.dataset.preSaleRelease=RELEASE;
let scheduled=false;const setText=(el,value)=>{if(el&&el.textContent!==value)el.textContent=value};const applyIdentity=()=>{scheduled=false;const title='Pré-Venda Samsung • v'+RELEASE;if(document.title!==title)document.title=title;setText(document.querySelector('.footer-note'),'PRÉ-VENDA SAMSUNG • v'+RELEASE.toUpperCase());setText(document.querySelector('#enterpriseSidebar .ent-sidebar-foot span'),'v'+RELEASE);setText(document.querySelector('.enterprise-sidebar-footer small, .sidebar-footer small, [data-system-version]'),'v'+RELEASE)};const scheduleIdentity=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(applyIdentity)};
const loadScript=(src,marker)=>new Promise((resolve,reject)=>{if(document.querySelector('script[data-v7-module="'+marker+'"]'))return resolve();const s=document.createElement('script');s.src=src;s.async=false;s.dataset.v7Module=marker;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
const loadInfrastructure=async()=>{if(window.__V741_INFRA_LOADED__)return;window.__V741_INFRA_LOADED__=true;try{await loadScript('./v741-deploy-guard.js?release='+RELEASE,'v741-guard');await loadScript('./v71-config.js?release='+RELEASE,'v71-config');await loadScript('./v71-data.js?release='+RELEASE,'v71-data');await loadScript('./v71-budget-import.js?release='+RELEASE,'v71-budget-import');await loadScript('./v71-integration.js?release='+RELEASE,'v71-integration');await loadScript('./v711-stability.js?release='+RELEASE,'v711-stability');await loadScript('./v72-core.js?release='+RELEASE,'v72-core');await loadScript('./v73-operations.js?release='+RELEASE,'v73-operations');await loadScript('./v74-polish.js?release='+RELEASE,'v74-polish')}catch(e){document.documentElement.dataset.v741Infra='load-error';console.error('[V7.4.1] infrastructure module failed',e)}};
const loadValidation=async()=>{if(window.__V741_VALIDATION_LOADED__)return;window.__V741_VALIDATION_LOADED__=true;try{await loadScript('./budget-catalog-refresh-v702.js?release='+STABLE_BASE,'budget-refresh');await loadScript('./pre-sale-watches-v7.js?release='+STABLE_BASE,'watches');await loadInfrastructure();await loadScript('./v7-smoke-test.js?release='+RELEASE,'smoke');await loadScript('./v71-self-test.js?release='+RELEASE,'v741-self-test')}catch(e){document.documentElement.dataset.v7Smoke='load-error';console.error('[V7.4.1] validation failed to load',e)}};
applyIdentity();const root=document.body||document.documentElement;if(root)new MutationObserver(scheduleIdentity).observe(root,{childList:true,subtree:true});window.addEventListener('load',()=>{scheduleIdentity();setTimeout(loadValidation,100)},{once:true});setTimeout(()=>{applyIdentity();window.preSaleReleaseBoot?.()},0);if(document.readyState==='complete')setTimeout(loadValidation,100);console.info('[Pré-Venda Samsung] verified release',RELEASE);
})();
