(()=>{
'use strict';
const VERSION='7.2.0';
const QUEUE_KEY='preVendaV72Queue';
const BACKUP_KEY='preVendaV72LastSnapshot';
const CHANNEL='pre-venda-v72';
const channel=('BroadcastChannel'in window)?new BroadcastChannel(CHANNEL):null;
const now=()=>new Date().toISOString();
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));return v};
const queue=()=>read(QUEUE_KEY,[]);
let flushing=false,lastSync=0;
function state(text,kind='ok'){window.dispatchEvent(new CustomEvent('v72:status',{detail:{text,kind,at:now()}}));document.documentElement.dataset.v72Status=kind}
function enqueue(op){const q=queue();q.push({id:crypto.randomUUID(),at:now(),attempts:0,...op});write(QUEUE_KEY,q);state('Sync pendente','pending');channel?.postMessage({type:'queue'});return q.length}
async function flush(){if(flushing||!navigator.onLine)return false;flushing=true;state('Sincronizando','sync');try{const q=queue(),keep=[];for(const item of q){try{if(item.kind==='request')await window.V71Data.request(item.path,item.options||{});else if(item.kind==='upsert')await window.V71Data[item.repo].upsert(item.data);else if(item.kind==='remove')await window.V71Data[item.repo].remove(item.id)}catch(e){item.attempts=(item.attempts||0)+1;item.error=String(e.message||e);if(item.attempts<8)keep.push(item)}}write(QUEUE_KEY,keep);lastSync=Date.now();state(keep.length?'Sync pendente':'Online',keep.length?'pending':'ok');return !keep.length}finally{flushing=false}}
async function safe(kind,payload){try{if(!navigator.onLine)throw new Error('offline');if(kind==='upsert')return await window.V71Data[payload.repo].upsert(payload.data);if(kind==='remove')return await window.V71Data[payload.repo].remove(payload.id);return await window.V71Data.request(payload.path,payload.options||{})}catch(e){enqueue({kind,...payload});return null}}
async function snapshot(reason='auto'){if(!window.V71Data)return null;const snap={version:VERSION,reason,at:now(),history:typeof getHistory==='function'?getHistory():[],budgets:read('samsung_saved_budgets_v1',[]),budgetCatalog:window.V71Data.budgetCatalog?.cached?.()||[],ecosystem:window.V71Data.ecosystem?.cached?.()||[]};write(BACKUP_KEY,snap);try{await window.V71Data.request('data_backups',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:crypto.randomUUID(),release:VERSION,reason,payload:snap,created_at:snap.at})})}catch(e){console.warn('[V7.2 backup]',e)}return snap}
function restoreLocal(){return read(BACKUP_KEY,null)}
async function tombstone(scope,id){if(!id)return;const row={scope,record_id:String(id),deleted_at:now(),release:VERSION};try{await window.V71Data.request('sync_tombstones?on_conflict=scope,record_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)})}catch(e){enqueue({kind:'request',path:'sync_tombstones?on_conflict=scope,record_id',options:{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)}})}}
async function tombstones(scope){try{return await window.V71Data.request(`sync_tombstones?scope=eq.${encodeURIComponent(scope)}&select=record_id,deleted_at`)||[]}catch{return[]}}
async function filterDeleted(scope,rows){const dead=new Set((await tombstones(scope)).map(x=>String(x.record_id)));return (rows||[]).filter(x=>!dead.has(String(x.id||x.record_id)))}
function wrapDeletion(){const old=window.deleteRecord;if(typeof old!=='function'||old.__v72)return;const wrapped=async function(id){await snapshot('before-delete');const result=await old.apply(this,arguments);await tombstone('pre_vendas',id);channel?.postMessage({type:'deleted',scope:'pre_vendas',id});return result};wrapped.__v72=true;window.deleteRecord=wrapped}
function preventDoubleClick(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||b.dataset.v72Busy==='1')return;if(/salvar|sincronizar|importar/i.test(b.textContent||'')){b.dataset.v72Busy='1';const old=b.textContent;b.disabled=true;setTimeout(()=>{b.disabled=false;b.dataset.v72Busy='0';b.textContent=old},900)}},true)}
function optimizeRendering(){const style=document.createElement('style');style.textContent='.table-wrap,.history-list,.budget-items{content-visibility:auto;contain-intrinsic-size:600px}#v72SyncBadge[data-kind="ok"]{background:#0f766e}#v72SyncBadge[data-kind="sync"]{background:#1d4ed8}#v72SyncBadge[data-kind="pending"]{background:#b45309}#v72SyncBadge[data-kind="off"]{background:#6b7280}';document.head.appendChild(style);for(const href of ['https://thhhpzxlletdhhhprawv.supabase.co','https://cdn.jsdelivr.net']){if(document.querySelector(`link[href="${href}"]`))continue;const l=document.createElement('link');l.rel='preconnect';l.href=href;l.crossOrigin='anonymous';document.head.appendChild(l)}if('PerformanceObserver'in window){try{const obs=new PerformanceObserver(list=>{window.V72_PERF={...(window.V72_PERF||{}),longTasks:(window.V72_PERF?.longTasks||0)+list.getEntries().length}});obs.observe({entryTypes:['longtask']})}catch{}}}
function installStatus(){document.getElementById('v711SyncStatus')?.remove();if(document.getElementById('v72SyncBadge'))return;const badge=document.createElement('button');badge.id='v72SyncBadge';badge.type='button';badge.setAttribute('role','status');badge.style.cssText='position:fixed;right:12px;bottom:12px;z-index:9999;border:0;padding:8px 11px;border-radius:999px;background:#111;color:white;font:600 12px system-ui;box-shadow:0 4px 18px #0003;cursor:pointer';badge.textContent=navigator.onLine?'Online':'Offline';badge.onclick=()=>{state('Sincronizando','sync');flush().then(refresh)};document.body.appendChild(badge);window.addEventListener('v72:status',e=>{badge.textContent=e.detail.text;badge.dataset.kind=e.detail.kind;badge.title='V7.2.0 • toque para sincronizar agora'})}
async function refresh(){if(!window.V71Data||Date.now()-lastSync<12000)return;lastSync=Date.now();try{const [b,c,e]=await Promise.all([window.V71Data.budgets.list(),window.V71Data.budgetCatalog.list(),window.V71Data.ecosystem.list()]);const fb=await filterDeleted('budgets',b);localStorage.setItem('samsung_budget_history_v71',JSON.stringify(fb));localStorage.setItem('samsung_budget_catalog_v71',JSON.stringify(c));localStorage.setItem('samsung_ecosystem_catalog_v71',JSON.stringify(e));state('Online','ok');channel?.postMessage({type:'refresh'})}catch{state('Offline','off')}}
function wire(){optimizeRendering();installStatus();preventDoubleClick();wrapDeletion();window.addEventListener('online',()=>{state('Sincronizando','sync');flush().then(refresh)});window.addEventListener('offline',()=>state('Offline','off'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('focus',refresh);channel?.addEventListener('message',e=>{if(e.data?.type==='queue')flush();if(['refresh','deleted'].includes(e.data?.type))requestAnimationFrame(()=>{window.renderHistory?.();window.renderDashboard?.()})});setInterval(()=>{flush();refresh()},30000);setInterval(()=>snapshot('periodic'),6*60*60*1000);setTimeout(()=>{flush();refresh();snapshot('boot')},1400)}
window.V72Core=Object.freeze({version:VERSION,enqueue,flush,safe,snapshot,restoreLocal,tombstone,filterDeleted,refresh});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();
