(()=>{
'use strict';
const VERSION='8.6.5';
const QUEUE_KEY='preVendaV72Queue',BACKUP_KEY='preVendaV72LastSnapshot',CHANNEL='pre-venda-v72';
const channel=('BroadcastChannel'in window)?new BroadcastChannel(CHANNEL):null,now=()=>new Date().toISOString();
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));return v};
const queue=()=>read(QUEUE_KEY,[]);let flushing=false,lastSync=0;
function state(text,kind='ok'){window.dispatchEvent(new CustomEvent('v72:status',{detail:{text,kind,at:now()}}));document.documentElement.dataset.v72Status=kind}
function enqueue(op){const q=queue();q.push({id:crypto.randomUUID(),at:now(),attempts:0,...op});write(QUEUE_KEY,q);state('Sync pendente','pending');channel?.postMessage({type:'queue'});return q.length}
async function flush(){if(flushing||!navigator.onLine)return false;flushing=true;state('Sincronizando','sync');try{const q=queue(),keep=[];for(const item of q){try{if(item.kind==='request')await window.V71Data.request(item.path,item.options||{});else if(item.kind==='upsert')await window.V71Data[item.repo].upsert(item.data);else if(item.kind==='remove')await window.V71Data[item.repo].remove(item.id)}catch(e){item.attempts=(item.attempts||0)+1;item.error=String(e.message||e);if(item.attempts<8)keep.push(item)}}write(QUEUE_KEY,keep);lastSync=Date.now();state(keep.length?'Sync pendente':'Online',keep.length?'pending':'ok');return !keep.length}finally{flushing=false}}
async function safe(kind,payload){try{if(!navigator.onLine)throw new Error('offline');let out;if(kind==='upsert')out=await window.V71Data[payload.repo].upsert(payload.data);else if(kind==='remove')out=await window.V71Data[payload.repo].remove(payload.id);else out=await window.V71Data.request(payload.path,payload.options||{});lastSync=Date.now();state('Online','ok');window.dispatchEvent(new CustomEvent('pre-sale:v865-mutated',{detail:{kind,...payload,at:lastSync}}));return out}catch(e){enqueue({kind,...payload});return null}}
async function snapshot(reason='action'){if(!window.V71Data)return null;const snap={version:VERSION,reason,at:now(),history:typeof getHistory==='function'?getHistory():[],budgets:read('samsung_saved_budgets_v1',[]),budgetCatalog:window.V71Data.budgetCatalog?.cached?.()||[],ecosystem:window.V71Data.ecosystem?.cached?.()||[]};write(BACKUP_KEY,snap);return snap}
function restoreLocal(){return read(BACKUP_KEY,null)}
async function tombstone(scope,id){if(!id)return;const row={scope,record_id:String(id),deleted_at:now(),release:VERSION};await safe('request',{path:'sync_tombstones?on_conflict=scope,record_id',options:{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)}})}
async function tombstones(scope){try{return await window.V71Data.request(`sync_tombstones?scope=eq.${encodeURIComponent(scope)}&select=record_id,deleted_at`)||[]}catch{return[]}}
async function filterDeleted(scope,rows){const dead=new Set((await tombstones(scope)).map(x=>String(x.record_id)));return(rows||[]).filter(x=>!dead.has(String(x.id||x.record_id)))}
function wrapDeletion(){const old=window.deleteRecord;if(typeof old!=='function'||old.__v865)return;const wrapped=async function(id){await snapshot('before-delete');const result=await old.apply(this,arguments);await tombstone('pre_vendas',id);channel?.postMessage({type:'deleted',scope:'pre_vendas',id});window.dispatchEvent(new CustomEvent('pre-sale:v865-mutated',{detail:{kind:'delete',scope:'pre_vendas',id,at:Date.now()}}));return result};wrapped.__v865=true;window.deleteRecord=wrapped}
function preventDoubleClick(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||b.dataset.v72Busy==='1')return;if(/salvar|sincronizar|importar/i.test(b.textContent||'')){b.dataset.v72Busy='1';const old=b.textContent;b.disabled=true;setTimeout(()=>{if(b.isConnected){b.disabled=false;b.dataset.v72Busy='0';b.textContent=old}},900)}},true)}
function optimizeRendering(){const style=document.createElement('style');style.textContent='.table-wrap,.history-list,.budget-items{content-visibility:auto;contain-intrinsic-size:600px}#v72SyncBadge[data-kind="ok"]{background:#0f766e}#v72SyncBadge[data-kind="sync"]{background:#1d4ed8}#v72SyncBadge[data-kind="pending"]{background:#b45309}#v72SyncBadge[data-kind="off"]{background:#6b7280}';document.head.appendChild(style)}
function installStatus(){document.getElementById('v711SyncStatus')?.remove();if(document.getElementById('v72SyncBadge'))return;const badge=document.createElement('button');badge.id='v72SyncBadge';badge.type='button';badge.style.cssText='position:fixed;right:12px;bottom:12px;z-index:9999;border:0;padding:8px 11px;border-radius:999px;background:#111;color:white;font:600 12px system-ui;box-shadow:0 4px 18px #0003;cursor:pointer';badge.textContent=navigator.onLine?'Online':'Offline';badge.onclick=async()=>{state('Sincronizando','sync');await flush();await window.V711_STABILITY?.refresh?.(true)};document.body.appendChild(badge);window.addEventListener('v72:status',e=>{badge.textContent=e.detail.text;badge.dataset.kind=e.detail.kind;badge.title='V8.6.5 • sincronização por ação'})}
async function refresh(){return window.V711_STABILITY?.refresh?.(true)??false}
function wire(){optimizeRendering();installStatus();preventDoubleClick();wrapDeletion();window.addEventListener('online',()=>{state('Sincronizando','sync');flush()});window.addEventListener('offline',()=>state('Offline','off'));channel?.addEventListener('message',e=>{if(e.data?.type==='queue')flush();if(e.data?.type==='deleted')requestAnimationFrame(()=>{window.renderHistory?.();window.renderDashboard?.()})});setTimeout(()=>{flush();snapshot('boot')},1400)}
window.V72Core=Object.freeze({version:VERSION,enqueue,flush,safe,snapshot,restoreLocal,tombstone,filterDeleted,refresh});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();