(()=>{
'use strict';
const VERSION='7.4.0';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const history=()=>{try{return typeof window.getHistory==='function'?window.getHistory():[]}catch{return[]}};
const stage=(id)=>window.V73Operations?.getStage?.('pre_vendas',id)||'Pré-venda';
const dt=v=>{const d=new Date(v||0);return Number.isNaN(+d)?null:d};
function insights(){const rows=history(),now=Date.now(),stale=rows.filter(r=>{const s=stage(r.id),d=dt(r.updatedAt||r.data);return !['Faturada','Cancelada'].includes(s)&&d&&now-d>72*3600000}),confirmed=rows.filter(r=>stage(r.id)==='Confirmada'),fat=rows.filter(r=>stage(r.id)==='Faturada');const bySeller={};rows.forEach(r=>{const k=r.vendedor||'Sem consultor';bySeller[k]??={total:0,fat:0};bySeller[k].total++;if(stage(r.id)==='Faturada')bySeller[k].fat++});return{rows,stale,confirmed,fat,ranking:Object.entries(bySeller).map(([name,x])=>({name,...x,conversion:x.total?Math.round(x.fat/x.total*100):0})).sort((a,b)=>b.fat-a.fat||b.conversion-a.conversion)}}
function renderOps(){const host=document.getElementById('v73Management');if(!host)return;let box=document.getElementById('v74Ops');if(!box){box=document.createElement('section');box.id='v74Ops';box.style.cssText='margin-top:16px';host.appendChild(box)}const x=insights();box.innerHTML=`<div class="dash-section"><h3>Visão gerencial</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px"><div class="dash-card"><span>Pendentes +72h</span><strong>${x.stale.length}</strong></div><div class="dash-card"><span>Confirmadas a faturar</span><strong>${x.confirmed.length}</strong></div><div class="dash-card"><span>Faturadas</span><strong>${x.fat.length}</strong></div></div></div><div class="dash-section"><h3>Ranking comercial</h3><div class="table-wrap"><table><thead><tr><th>Consultor</th><th>Pré-vendas</th><th>Faturadas</th><th>Conversão</th></tr></thead><tbody>${x.ranking.slice(0,15).map(r=>`<tr><td>${esc(r.name)}</td><td>${r.total}</td><td>${r.fat}</td><td>${r.conversion}%</td></tr>`).join('')||'<tr><td colspan="4">Sem dados.</td></tr>'}</tbody></table></div></div>${x.stale.length?`<div class="dash-section"><h3>Pendências comerciais</h3><div class="muted-box">${x.stale.slice(0,20).map(r=>`${esc(r.cliente||'Cliente')} • ${esc(r.produto||'Produto')} • ${esc(stage(r.id))}`).join('<br>')}</div></div>`:''}`}
async function renderAudit(){const host=document.getElementById('v73Audit');if(!host||!window.V71Data)return;let rows=[];try{rows=await window.V71Data.request('audit_events?select=*&order=created_at.desc&limit=300')||[]}catch{return}host.innerHTML=`<h3>Auditoria operacional</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0"><input id="v74AuditSearch" placeholder="Buscar ação, entidade ou registro"><select id="v74AuditAction"><option value="">Todas as ações</option>${[...new Set(rows.map(x=>x.action))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="v74AuditList" style="max-height:390px;overflow:auto"></div>`;const draw=()=>{const q=(document.getElementById('v74AuditSearch')?.value||'').toLowerCase(),a=document.getElementById('v74AuditAction')?.value||'',filtered=rows.filter(x=>(!a||x.action===a)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));document.getElementById('v74AuditList').innerHTML=filtered.map(x=>`<div class="audit-item"><strong>${esc(x.action)}</strong><br><small>${new Date(x.created_at).toLocaleString('pt-BR')} • ${esc(x.entity_type)}${x.entity_id?' • '+esc(x.entity_id):''}</small></div>`).join('')||'<div class="empty">Nenhum evento encontrado.</div>'};document.getElementById('v74AuditSearch').oninput=draw;document.getElementById('v74AuditAction').onchange=draw;draw()}
function exportPipeline(){const rows=history(),cols=['Cliente','Produto','Consultor','Etapa'];const data=[cols,...rows.map(r=>[r.cliente||'',r.produto||'',r.vendedor||'',stage(r.id)])];const csv=data.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pipeline-pre-venda-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function addExport(){const host=document.getElementById('v73Management');if(!host||document.getElementById('v74Export'))return;const b=document.createElement('button');b.id='v74Export';b.className='btn secondary';b.textContent='Exportar pipeline CSV';b.onclick=exportPipeline;host.prepend(b)}
function boot(){const ops=window.V73Operations;if(ops&&!ops.getStage)ops.getStage=(type,id)=>{try{return document.querySelector(`select[data-v73-id="${CSS.escape(String(id))}"]`)?.value||'Pré-venda'}catch{return'Pré-venda'}};renderOps();renderAudit();addExport();setInterval(renderOps,60000);window.V74Polish={version:VERSION,renderOps,renderAudit,exportPipeline}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,2600),{once:true});else setTimeout(boot,2600);
})();
