(()=>{
'use strict';
const VERSION='8.4.0';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=()=>typeof window.getFilteredHistoryView==='function'?window.getFilteredHistoryView():(typeof window.getHistory==='function'?window.getHistory():[]);
function removeBudgetHistory(){
 for(const id of ['historyModeBar','budgetHistoryTools','budgetHistoryContent'])$(id)?.remove();
 const mode=$('historyMode');mode?.closest('.budget-history-switch')?.remove();
 const save=$('budgetSave');if(save){save.hidden=true;save.style.display='none'}
 const head=$('budgetPanel')?.querySelector('.budget-head p');if(head)head.textContent='Orçamento avulso para impressão. Este documento não é salvo no histórico.';
 window.saveBudgetRecord=()=>{window.budgetApp?.print?.('a4')};
}
function statusOf(x){return x.statusVenda||'Aguardando produto'}
function ensureHeader(){
 const panel=$('historyPanel'),card=panel?.querySelector('.card');if(!card)return;
 let head=$('v84HistoryHead');if(!head){head=document.createElement('div');head.id='v84HistoryHead';head.className='v84-history-head';head.innerHTML='<div><span>GESTÃO DE PRÉ-VENDAS</span><h2>Histórico de Pré-vendas</h2><p>Consulte, filtre e acompanhe exclusivamente as pré-vendas registradas.</p></div><button type="button" class="btn-outline" id="v84ClearHistoryFilters">Limpar filtros</button>';card.prepend(head);$('v84ClearHistoryFilters').onclick=clearFilters}
 let kpis=$('v84HistoryKpis');if(!kpis){kpis=document.createElement('div');kpis.id='v84HistoryKpis';kpis.className='v84-history-kpis';head.insertAdjacentElement('afterend',kpis)}
 let quick=$('v84QuickFilters');if(!quick){quick=document.createElement('div');quick.id='v84QuickFilters';quick.className='v84-history-quick';quick.innerHTML='<button data-q="all" class="active">Todas</button><button data-q="waiting">Aguardando</button><button data-q="advised">Cliente avisado</button><button data-q="retired">Retirado</button><button data-q="eco">Com ecossistema</button>';kpis.insertAdjacentElement('afterend',quick);quick.querySelectorAll('button').forEach(b=>b.onclick=()=>applyQuick(b.dataset.q,b))}
 const search=$('busca');if(search){search.placeholder='Buscar cliente, CPF, produto, cor, consultor...';search.setAttribute('aria-label','Buscar pré-venda')}
 const exportBtn=$('exportarBtn');if(exportBtn)exportBtn.textContent='Exportar pré-vendas';
}
function clearFilters(){for(const id of ['busca','histStart','histEnd','histConsultant','histProduct','histStatus','histEco']){const el=$(id);if(el)el.value=''}window.getSelectedHistoryProducts?.().forEach(()=>{});$('histProductClear')?.click();document.querySelectorAll('#v84QuickFilters button').forEach((b,i)=>b.classList.toggle('active',i===0));window.renderHistory?.()}
function applyQuick(q,button){document.querySelectorAll('#v84QuickFilters button').forEach(b=>b.classList.toggle('active',b===button));if($('histStatus'))$('histStatus').value='';if($('histEco'))$('histEco').value='';if(q==='waiting'&&$('histStatus'))$('histStatus').value='Aguardando produto';if(q==='advised'&&$('histStatus'))$('histStatus').value='Cliente avisado';if(q==='retired'&&$('histStatus'))$('histStatus').value='Retirado';if(q==='eco'&&$('histEco'))$('histEco').value='com';window.renderHistory?.()}
function renderKpis(){const list=rows(),all=typeof window.getHistory==='function'?window.getHistory():list,waiting=list.filter(x=>statusOf(x)==='Aguardando produto').length,advised=list.filter(x=>statusOf(x)==='Cliente avisado').length,retired=list.filter(x=>statusOf(x)==='Retirado').length,eco=list.filter(x=>!!x.wearable).length;const box=$('v84HistoryKpis');if(!box)return;box.innerHTML=`<div><span>Resultados</span><strong>${list.length}</strong><small>de ${all.length} pré-vendas</small></div><div><span>Aguardando</span><strong>${waiting}</strong><small>produto pendente</small></div><div><span>Cliente avisado</span><strong>${advised}</strong><small>aguardando retirada</small></div><div><span>Retirados</span><strong>${retired}</strong><small>concluídos</small></div><div><span>Ecossistema</span><strong>${eco}</strong><small>com wearable</small></div>`}
function polishContent(){const content=$('historyContent');if(!content)return;content.classList.add('v84-history-content');content.querySelectorAll('table').forEach(t=>t.classList.add('v84-history-table'));content.querySelectorAll('tr').forEach(tr=>tr.classList.add('v84-history-row'));const meta=content.querySelector('.history-meta');if(meta)meta.classList.add('v84-history-meta')}
function wrapRender(){const old=window.renderHistory;if(typeof old!=='function'||old.__v84)return;const fn=function(){removeBudgetHistory();ensureHeader();const result=old.apply(this,arguments);renderKpis();polishContent();return result};fn.__v84=true;window.renderHistory=fn}
function installStyles(){if($('v84HistoryStyle'))return;const s=document.createElement('style');s.id='v84HistoryStyle';s.textContent=`
#historyPanel>.card{overflow:visible}.v84-history-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;padding:22px 22px 16px;border-bottom:1px solid #e8ecf3}.v84-history-head span{font-size:10px;letter-spacing:.12em;font-weight:900;color:#526079}.v84-history-head h2{margin:4px 0 4px;font-size:24px;color:#101828}.v84-history-head p{margin:0;color:#667085;font-size:13px}.v84-history-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;padding:16px 22px}.v84-history-kpis>div{padding:14px 15px;border:1px solid #e5eaf2;border-radius:14px;background:linear-gradient(180deg,#fff,#f9fbff)}.v84-history-kpis span{display:block;font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.04em;color:#667085}.v84-history-kpis strong{display:block;font-size:26px;line-height:1.1;margin:6px 0 3px;color:#101828}.v84-history-kpis small{font-size:10px;color:#98a2b3}.v84-history-quick{display:flex;gap:7px;flex-wrap:wrap;padding:0 22px 14px}.v84-history-quick button{border:1px solid #dce2eb;background:#fff;color:#475467;border-radius:999px;padding:8px 12px;font-weight:750;font-size:11px}.v84-history-quick button.active{background:#1428a0;color:#fff;border-color:#1428a0}.history-filters,.history-toolbar,#historyPanel .toolbar{gap:9px}.v84-history-content .table-wrap{border:1px solid #e7ebf1;border-radius:14px;overflow:auto}.v84-history-table{border-collapse:separate;border-spacing:0}.v84-history-table thead th{position:sticky;top:0;background:#f8fafc;color:#475467;font-size:10px;text-transform:uppercase;letter-spacing:.04em;z-index:1}.v84-history-table tbody tr:hover{background:#f8fbff}.v84-history-table td{vertical-align:middle;border-bottom:1px solid #eef1f5}.v84-history-meta{padding:10px 2px;color:#667085;font-size:12px}
@media(max-width:900px){.v84-history-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:700px){#historyPanel>.card{border-radius:0}.v84-history-head{align-items:flex-start;padding:18px 16px 12px}.v84-history-head h2{font-size:21px}.v84-history-head p{font-size:12px;max-width:250px}.v84-history-head .btn-outline{padding:8px 10px;white-space:nowrap}.v84-history-kpis{grid-template-columns:repeat(2,minmax(0,1fr));padding:12px 16px;gap:8px}.v84-history-kpis>div:first-child{grid-column:1/-1}.v84-history-kpis strong{font-size:23px}.v84-history-quick{padding:0 16px 12px;overflow:auto;flex-wrap:nowrap}.v84-history-quick button{white-space:nowrap}.history-filters,#historyPanel .toolbar{display:grid!important;grid-template-columns:1fr 1fr!important;padding-left:16px!important;padding-right:16px!important}.history-filters #busca,#historyPanel .toolbar #busca,.hist-product-multi{grid-column:1/-1}.v84-history-content .table-wrap{border:0;border-radius:0}.v84-history-content table,.v84-history-content thead,.v84-history-content tbody,.v84-history-content tr,.v84-history-content td{display:block}.v84-history-content thead{display:none}.v84-history-content tr{margin:10px 16px;padding:14px;border:1px solid #e5eaf2;border-radius:14px;background:#fff;box-shadow:0 4px 14px rgba(16,24,40,.05)}.v84-history-content td{border:0!important;padding:5px 0!important}.v84-history-content td:last-child{padding-top:10px!important;border-top:1px solid #eef1f5!important;margin-top:6px}}
`;document.head.appendChild(s)}
function boot(){removeBudgetHistory();installStyles();wrapRender();ensureHeader();window.renderHistory?.();const sw=window.switchTab;if(typeof sw==='function'&&!sw.__v84){const fn=function(id){const r=sw.apply(this,arguments);if(id==='historyPanel')setTimeout(()=>{removeBudgetHistory();ensureHeader();window.renderHistory?.()},0);if(id==='budgetPanel')setTimeout(removeBudgetHistory,0);return r};fn.__v84=true;window.switchTab=fn}window.V84History={version:VERSION,removeBudgetHistory,renderKpis,clearFilters}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,2600),{once:true});else setTimeout(boot,2600);
})();